export const FORM_SECTIONS = [
  {
    icon: '🧊',
    title: 'الثلاجات',
    sub: 'Refrigerators',
    products: [
      {
        id: 'card_cat0_0',
        brand: 'beko',
        model: 'RDNG491M20SXB (Egypt)  RDNG491M20BP (Egypt)',
        existsName: 'cat0_0_exists',
        competitors: [
          { brand: 'Bosch', model: 'KDN43VL2M8', ref: '450 JD', priceName: 'cat0_0_c0', availName: 'cat0_0_c0_avail' },
          { brand: 'Toshiba', model: 'GR-RT468WE-PMF(37)', ref: '329 JD', priceName: 'cat0_0_c1', availName: 'cat0_0_c1_avail' },
          { brand: 'Midea', model: 'MDRT489MTE46', ref: '299 JD', priceName: 'cat0_0_c2', availName: 'cat0_0_c2_avail' },
          { brand: 'Hisense', model: 'RT488N4ASU', ref: '369 JD', priceName: 'cat0_0_c3', availName: 'cat0_0_c3_avail' },
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'cat0_0_c4', availName: 'cat0_0_c4_avail' },
          { brand: 'Sharp', model: 'SJ-58C', ref: '329 JD', priceName: 'cat0_0_c5', availName: 'cat0_0_c5_avail' },
          { brand: 'beko', model: 'RDNG491M20BP', ref: '329 JD', priceName: 'cat0_0_c6', availName: 'cat0_0_c6_avail' },
          { brand: 'beko', model: 'RDNG491M20SXB', ref: '329 JD', priceName: 'cat0_0_c7', availName: 'cat0_0_c7_avail' },
        ],
      },
      {
        id: 'card_cat0_1',
        brand: 'beko',
        model: 'RDNG551M20TSX (Egypt)  RDNG551M20TXBR (Egypt)',
        existsName: 'cat0_1_exists',
        competitors: [
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'cat0_1_c0', availName: 'cat0_1_c0_avail' },
          { brand: 'Toshiba', model: 'GR-RT559WE-PMF(37)', ref: '369 JD', priceName: 'cat0_1_c1', availName: 'cat0_1_c1_avail' },
          { brand: 'Midea', model: 'MDRT580MTE46D', ref: '349 JD', priceName: 'cat0_1_c2', availName: 'cat0_1_c2_avail' },
          { brand: 'Sharp', model: 'SJ-58C', ref: '329 JD', priceName: 'cat0_1_c3', availName: 'cat0_1_c3_avail' },
          { brand: 'Samsung', model: 'RT47CG6002S9JO', ref: '499 JD', priceName: 'cat0_1_c4', availName: 'cat0_1_c4_avail' },
          { brand: 'beko', model: 'RDNG551M20TSX', ref: '369 JD', priceName: 'cat0_1_c5', availName: 'cat0_1_c5_avail' },
          { brand: 'beko', model: 'RDNG551M20TXBR', ref: '379 JD', priceName: 'cat0_1_c6', availName: 'cat0_1_c6_avail' },
        ],
      },
      {
        id: 'card_cat0_2',
        brand: 'Ariston',
        model: 'ART70 F1452 XLE',
        existsName: 'cat0_2_exists',
        competitors: [
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'cat0_2_c0', availName: 'cat0_2_c0_avail' },
          { brand: 'Ariston', model: 'ART70 F1452 XLE', ref: '529 JD', priceName: 'cat0_2_c1', availName: 'cat0_2_c1_avail' },
          { brand: 'Toshiba', model: 'GR-RT559WE-PMF(37)', ref: '369 JD', priceName: 'cat0_2_c2', availName: 'cat0_2_c2_avail' },
          { brand: 'Whirlpool', model: 'W7TI 8711 NFX EX', ref: '549 JD', priceName: 'cat0_2_c3', availName: 'cat0_2_c3_avail' },
          { brand: 'Electrolux', model: 'ETB4600B-A', ref: '699 JD', priceName: 'cat0_2_c4', availName: 'cat0_2_c4_avail' },
          { brand: 'Indesit', model: 'I7TM 8111 NFX UK EX', ref: '549 JD', priceName: 'cat0_2_c5', availName: 'cat0_2_c5_avail' },
          { brand: 'LG', model: 'GLM-592LI.DPZPELF', ref: '499 JD', priceName: 'cat0_2_c6', availName: 'cat0_2_c6_avail' },
          { brand: 'Bosch', model: 'KDN55NL20U', ref: '600 JD', priceName: 'cat0_2_c7', availName: 'cat0_2_c7_avail' },
          { brand: 'LG', model: 'GNB-682FVFP.APYPELF', ref: '569 JD', priceName: 'cat0_2_c8', availName: 'cat0_2_c8_avail' },
          { brand: 'Samsung', model: 'RT47CG6002S9JO', ref: '499 JD', priceName: 'cat0_2_c9', availName: 'cat0_2_c9_avail' },
        ],
      },
      {
        id: 'card_cat0_3',
        brand: 'beko',
        model: 'B3RDNE66HXP',
        existsName: 'cat0_3_exists',
        competitors: [
          { brand: 'Hisense', model: 'RT599N4ASU', ref: '399 JD', priceName: 'cat0_3_c0', availName: 'cat0_3_c0_avail' },
          { brand: 'LG', model: 'GNM-732HLI.APZPELF', ref: '799 JD', priceName: 'cat0_3_c1', availName: 'cat0_3_c1_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'cat0_3_c2', availName: 'cat0_3_c2_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'cat0_3_c3', availName: 'cat0_3_c3_avail' },
          { brand: 'Hitachi', model: 'HRTN8565DF-BSL (New)', ref: '777 JD', priceName: 'cat0_3_c4', availName: 'cat0_3_c4_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'cat0_3_c5', availName: 'cat0_3_c5_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'cat0_3_c6', availName: 'cat0_3_c6_avail' },
          { brand: 'Sharp', model: 'SJ-SE72D', ref: '799 JD', priceName: 'cat0_3_c7', availName: 'cat0_3_c7_avail' },
          { brand: 'Bosch', model: 'KDN76XL30U', ref: '790 JD', priceName: 'cat0_3_c8', availName: 'cat0_3_c8_avail' },
          { brand: 'beko', model: 'B3RDNE66HXP', ref: '679 JD', priceName: 'cat0_3_c9', availName: 'cat0_3_c9_avail' },
          { brand: 'Hisense', model: 'RT729N4ASU', ref: '589 JD', priceName: 'cat0_3_c10', availName: 'cat0_3_c10_avail' },
        ],
      },
      {
        id: 'card_cat0_4',
        brand: 'Ariston',
        model: 'ART78 F6593 XLNA',
        existsName: 'cat0_4_exists',
        competitors: [
          { brand: 'LG', model: 'GNM-732HLI.APZPELF', ref: '799 JD', priceName: 'cat0_4_c0', availName: 'cat0_4_c0_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'cat0_4_c1', availName: 'cat0_4_c1_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'cat0_4_c2', availName: 'cat0_4_c2_avail' },
          { brand: 'Hitachi', model: 'HRTN8565DF-BSL (New)', ref: '777 JD', priceName: 'cat0_4_c3', availName: 'cat0_4_c3_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'cat0_4_c4', availName: 'cat0_4_c4_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'cat0_4_c5', availName: 'cat0_4_c5_avail' },
          { brand: 'Sharp', model: 'SJ-SE72D', ref: '799 JD', priceName: 'cat0_4_c6', availName: 'cat0_4_c6_avail' },
          { brand: 'Bosch', model: 'KDN76XL30U', ref: '790 JD', priceName: 'cat0_4_c7', availName: 'cat0_4_c7_avail' },
          { brand: 'Ariston', model: 'ART78 F6593 XLNA', ref: '849 JD', priceName: 'cat0_4_c8', availName: 'cat0_4_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_5',
        brand: 'beko',
        model: 'DN168121XB',
        existsName: 'cat0_5_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'cat0_5_c0', availName: 'cat0_5_c0_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'cat0_5_c1', availName: 'cat0_5_c1_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'cat0_5_c2', availName: 'cat0_5_c2_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'cat0_5_c3', availName: 'cat0_5_c3_avail' },
          { brand: 'Hisense', model: 'RT729N4ASU', ref: '589 JD', priceName: 'cat0_5_c4', availName: 'cat0_5_c4_avail' },
          { brand: 'beko', model: 'DN168121XB', ref: '649 JD', priceName: 'cat0_5_c5', availName: 'cat0_5_c5_avail' },
          { brand: 'Whirlpool', model: 'WTMF 836633 XNA', ref: '900 JD', priceName: 'cat0_5_c6', availName: 'cat0_5_c6_avail' },
          { brand: 'Indesit', model: 'I84TE 31 X EX', ref: '899 JD', priceName: 'cat0_5_c7', availName: 'cat0_5_c7_avail' },
          { brand: 'Sharp', model: 'SJ-GP77D-SL', ref: '999 JD', priceName: 'cat0_5_c8', availName: 'cat0_5_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_6',
        brand: 'beko',
        model: 'RDNE710E40SXP  RDNE710E40SXBR',
        existsName: 'cat0_6_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM850TF4E-XCL', ref: '599 JD', priceName: 'cat0_6_c0', availName: 'cat0_6_c0_avail' },
          { brand: 'Vestel', model: 'RM850TF4E-DXCL', ref: '609 JD', priceName: 'cat0_6_c1', availName: 'cat0_6_c1_avail' },
          { brand: 'Samsung', model: 'RT58K7000S8/JO', ref: '769 JD', priceName: 'cat0_6_c2', availName: 'cat0_6_c2_avail' },
          { brand: 'Sharp', model: 'SJ-GP77D-SL', ref: '999 JD', priceName: 'cat0_6_c3', availName: 'cat0_6_c3_avail' },
          { brand: 'LG', model: 'GRM-852HLI.APZPELF', ref: '939 JD', priceName: 'cat0_6_c4', availName: 'cat0_6_c4_avail' },
          { brand: 'beko', model: 'RDNE710E40SXP', ref: '779 JD', priceName: 'cat0_6_c5', availName: 'cat0_6_c5_avail' },
          { brand: 'beko', model: 'RDNE710E40SXBR', ref: '799 JD', priceName: 'cat0_6_c6', availName: 'cat0_6_c6_avail' },
          { brand: 'Whirlpool', model: 'WTMF 836653 XME', ref: '850 JD', priceName: 'cat0_6_c7', availName: 'cat0_6_c7_avail' },
          { brand: 'Hisense', model: 'RT3N635NAD4 (New)', ref: '749 JD', priceName: 'cat0_6_c8', availName: 'cat0_6_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_7',
        brand: 'beko',
        model: 'B5RCNE565HXPMG',
        existsName: 'cat0_7_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'cat0_7_c0', availName: 'cat0_7_c0_avail' },
          { brand: 'Whirlpool', model: 'W5 711E OX', ref: '450 JD', priceName: 'cat0_7_c1', availName: 'cat0_7_c1_avail' },
          { brand: 'Indesit', model: 'LD70 N1 X UK', ref: '499 JD', priceName: 'cat0_7_c2', availName: 'cat0_7_c2_avail' },
          { brand: 'Indesit', model: 'LI8 SN2E K', ref: '549 JD', priceName: 'cat0_7_c3', availName: 'cat0_7_c3_avail' },
          { brand: 'Indesit', model: 'XI9 T2I X', ref: '599 JD', priceName: 'cat0_7_c4', availName: 'cat0_7_c4_avail' },
          { brand: 'beko', model: 'B5RCNE565HXPMG', ref: '625 JD', priceName: 'cat0_7_c5', availName: 'cat0_7_c5_avail' },
          { brand: 'Hisense', model: 'RB5P504NMI3', ref: '649 JD', priceName: 'cat0_7_c6', availName: 'cat0_7_c6_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'cat0_7_c7', availName: 'cat0_7_c7_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'cat0_7_c8', availName: 'cat0_7_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_8',
        brand: 'beko',
        model: 'B5RCNE66HXB',
        existsName: 'cat0_8_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'cat0_8_c0', availName: 'cat0_8_c0_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'cat0_8_c1', availName: 'cat0_8_c1_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'cat0_8_c2', availName: 'cat0_8_c2_avail' },
          { brand: 'beko', model: 'B5RCNE66HXB', ref: '649 JD', priceName: 'cat0_8_c3', availName: 'cat0_8_c3_avail' },
        ],
      },
      {
        id: 'card_cat0_9',
        brand: 'Ariston',
        model: 'ARB78 F6593 XLNA',
        existsName: 'cat0_9_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'cat0_9_c0', availName: 'cat0_9_c0_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'cat0_9_c1', availName: 'cat0_9_c1_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'cat0_9_c2', availName: 'cat0_9_c2_avail' },
          { brand: 'beko', model: 'ARB78 F6593 XLNA', ref: '859 JD', priceName: 'cat0_9_c3', availName: 'cat0_9_c3_avail' },
        ],
      },
      {
        id: 'card_cat0_10',
        brand: 'Ariston',
        model: 'ARB78 F6593 XLNA',
        existsName: 'cat0_10_exists',
        competitors: [
          { brand: 'Ariston', model: 'ARB78 F6593 XLNA', ref: '859 JD', priceName: 'cat0_10_c0', availName: 'cat0_10_c0_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-DXCL', ref: '899 JD', priceName: 'cat0_10_c1', availName: 'cat0_10_c1_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-XCL', ref: '719 JD', priceName: 'cat0_10_c2', availName: 'cat0_10_c2_avail' },
          { brand: 'Whirlpool', model: 'WBMF 836573 XNA', ref: '900 JD', priceName: 'cat0_10_c3', availName: 'cat0_10_c3_avail' },
          { brand: 'Bosch', model: 'KGD86AI304', ref: '1099 JD', priceName: 'cat0_10_c4', availName: 'cat0_10_c4_avail' },
          { brand: 'Bosch', model: 'KGN86AI32U', ref: '999 JD', priceName: 'cat0_10_c5', availName: 'cat0_10_c5_avail' },
        ],
      },
      {
        id: 'card_cat0_11',
        brand: 'beko',
        model: 'RCNE730E40SXP',
        existsName: 'cat0_11_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM850BF4E-DXCL', ref: '899 JD', priceName: 'cat0_11_c0', availName: 'cat0_11_c0_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-XCL', ref: '719 JD', priceName: 'cat0_11_c1', availName: 'cat0_11_c1_avail' },
          { brand: 'beko', model: 'RCNE730E40SXP', ref: '799 JD', priceName: 'cat0_11_c2', availName: 'cat0_11_c2_avail' },
          { brand: 'Whirlpool', model: 'WBMF 836573 XNA', ref: '900 JD', priceName: 'cat0_11_c3', availName: 'cat0_11_c3_avail' },
          { brand: 'Bosch', model: 'KGD86AI304', ref: '1099 JD', priceName: 'cat0_11_c4', availName: 'cat0_11_c4_avail' },
          { brand: 'Bosch', model: 'KGN86AI32U', ref: '999 JD', priceName: 'cat0_11_c5', availName: 'cat0_11_c5_avail' },
        ],
      },
      {
        id: 'card_cat0_12',
        brand: 'beko',
        model: 'GN156320XP',
        existsName: 'cat0_12_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS670N4ASU', ref: '549 JD', priceName: 'cat0_12_c0', availName: 'cat0_12_c0_avail' },
          { brand: 'Midea', model: 'MDRS710FGF02', ref: '550 JD', priceName: 'cat0_12_c1', availName: 'cat0_12_c1_avail' },
          { brand: 'beko', model: 'GN156320XP', ref: '599 JD', priceName: 'cat0_12_c2', availName: 'cat0_12_c2_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'cat0_12_c3', availName: 'cat0_12_c3_avail' },
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'cat0_12_c4', availName: 'cat0_12_c4_avail' },
        ],
      },
      {
        id: 'card_cat0_13',
        brand: 'beko',
        model: 'GN 164020XP',
        existsName: 'cat0_13_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'cat0_13_c0', availName: 'cat0_13_c0_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'cat0_13_c1', availName: 'cat0_13_c1_avail' },
          { brand: 'beko', model: 'GN 164020XP', ref: '799 JD', priceName: 'cat0_13_c2', availName: 'cat0_13_c2_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'cat0_13_c3', availName: 'cat0_13_c3_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'cat0_13_c4', availName: 'cat0_13_c4_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'cat0_13_c5', availName: 'cat0_13_c5_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'cat0_13_c6', availName: 'cat0_13_c6_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'cat0_13_c7', availName: 'cat0_13_c7_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'cat0_13_c8', availName: 'cat0_13_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_14',
        brand: 'beko',
        model: 'GN164022XBR',
        existsName: 'cat0_14_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'cat0_14_c0', availName: 'cat0_14_c0_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'cat0_14_c1', availName: 'cat0_14_c1_avail' },
          { brand: 'beko', model: 'GN164022XBR', ref: '799 JD', priceName: 'cat0_14_c2', availName: 'cat0_14_c2_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'cat0_14_c3', availName: 'cat0_14_c3_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'cat0_14_c4', availName: 'cat0_14_c4_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'cat0_14_c5', availName: 'cat0_14_c5_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'cat0_14_c6', availName: 'cat0_14_c6_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'cat0_14_c7', availName: 'cat0_14_c7_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'cat0_14_c8', availName: 'cat0_14_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_15',
        brand: 'beko',
        model: 'GN 164020 GB',
        existsName: 'cat0_15_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'cat0_15_c0', availName: 'cat0_15_c0_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'cat0_15_c1', availName: 'cat0_15_c1_avail' },
          { brand: 'beko', model: 'GN 164020 GB', ref: '999 JD', priceName: 'cat0_15_c2', availName: 'cat0_15_c2_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'cat0_15_c3', availName: 'cat0_15_c3_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'cat0_15_c4', availName: 'cat0_15_c4_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'cat0_15_c5', availName: 'cat0_15_c5_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'cat0_15_c6', availName: 'cat0_15_c6_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'cat0_15_c7', availName: 'cat0_15_c7_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'cat0_15_c8', availName: 'cat0_15_c8_avail' },
        ],
      },
      {
        id: 'card_cat0_16',
        brand: 'Ariston',
        model: 'ARS91 F6634 XLNA',
        existsName: 'cat0_16_exists',
        competitors: [
          { brand: 'Ariston', model: 'ARS91 F6634 XLNA', ref: '979 JD', priceName: 'cat0_16_c0', availName: 'cat0_16_c0_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'cat0_16_c1', availName: 'cat0_16_c1_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'cat0_16_c2', availName: 'cat0_16_c2_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'cat0_16_c3', availName: 'cat0_16_c3_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'cat0_16_c4', availName: 'cat0_16_c4_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'cat0_16_c5', availName: 'cat0_16_c5_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'cat0_16_c6', availName: 'cat0_16_c6_avail' },
        ],
      },
      {
        id: 'card_cat0_17',
        brand: 'beko',
        model: 'GN1406223PX',
        existsName: 'cat0_17_exists',
        competitors: [
          { brand: 'Samsung', model: 'RF48A4010M9/LV', ref: '999 JD', priceName: 'cat0_17_c0', availName: 'cat0_17_c0_avail' },
          { brand: 'Electrolux', model: 'EQE4900A-B', ref: '899 JD', priceName: 'cat0_17_c1', availName: 'cat0_17_c1_avail' },
          { brand: 'beko', model: 'GN1406223PX', ref: '1049 JD', priceName: 'cat0_17_c2', availName: 'cat0_17_c2_avail' },
          { brand: 'Hisense', model: 'RQ749N4ASU', ref: '1149 JD', priceName: 'cat0_17_c3', availName: 'cat0_17_c3_avail' },
          { brand: 'Hisense', model: 'RS819N4ISU', ref: '999 JD', priceName: 'cat0_17_c4', availName: 'cat0_17_c4_avail' },
        ],
      },
    ],
  },
  {
    icon: '🫧',
    title: 'الغسالات',
    sub: 'Washing Machines',
    products: [
      {
        id: 'card_cat1_0',
        brand: 'beko',
        model: 'BM1WFU37200BS',
        existsName: 'cat1_0_exists',
        competitors: [
          { brand: 'LG', model: 'FH2J3QDNP0.SBWPEL', ref: '299 JD', priceName: 'cat1_0_c0', availName: 'cat1_0_c0_avail' },
          { brand: 'Electrolux', model: 'EW6F5722BB', ref: '199 JD', priceName: 'cat1_0_c1', availName: 'cat1_0_c1_avail' },
          { brand: 'AEG', model: 'LFW6I7261B', ref: '333 JD', priceName: 'cat1_0_c2', availName: 'cat1_0_c2_avail' },
          { brand: 'Midea', model: 'MF100W70B', ref: '209 JD', priceName: 'cat1_0_c3', availName: 'cat1_0_c3_avail' },
          { brand: 'Sharp', model: 'ES-FE710DZL-S', ref: '269 JD', priceName: 'cat1_0_c4', availName: 'cat1_0_c4_avail' },
          { brand: 'Indesit', model: 'OMTWE 71252 S EU', ref: '300 JD', priceName: 'cat1_0_c5', availName: 'cat1_0_c5_avail' },
          { brand: 'Conti', model: 'WM 7123 SB', ref: '219 JD', priceName: 'cat1_0_c6', availName: 'cat1_0_c6_avail' },
          { brand: 'Samsung', model: 'WW70T4020CX1AS', ref: '279 JD', priceName: 'cat1_0_c7', availName: 'cat1_0_c7_avail' },
          { brand: 'beko', model: 'BM1WFU37200BS', ref: '229 JD', priceName: 'cat1_0_c8', availName: 'cat1_0_c8_avail' },
          { brand: 'Vestel', model: 'WB712T2DSS', ref: '209 JD', priceName: 'cat1_0_c9', availName: 'cat1_0_c9_avail' },
          { brand: 'Conti', model: 'WMP7124TB', ref: '199 JD', priceName: 'cat1_0_c10', availName: 'cat1_0_c10_avail' },
          { brand: 'Hisense', model: 'WFQP7012JT/P', ref: '219 JD', priceName: 'cat1_0_c11', availName: 'cat1_0_c11_avail' },
        ],
      },
      {
        id: 'card_cat1_1',
        brand: 'beko',
        model: 'BM3WFU38200BS',
        existsName: 'cat1_1_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'cat1_1_c0', availName: 'cat1_1_c0_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'cat1_1_c1', availName: 'cat1_1_c1_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'cat1_1_c2', availName: 'cat1_1_c2_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'cat1_1_c3', availName: 'cat1_1_c3_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'cat1_1_c4', availName: 'cat1_1_c4_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'cat1_1_c5', availName: 'cat1_1_c5_avail' },
          { brand: 'Midea', model: 'MF100W80B', ref: '249 JD', priceName: 'cat1_1_c6', availName: 'cat1_1_c6_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'cat1_1_c7', availName: 'cat1_1_c7_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'cat1_1_c8', availName: 'cat1_1_c8_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'cat1_1_c9', availName: 'cat1_1_c9_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'cat1_1_c10', availName: 'cat1_1_c10_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'cat1_1_c11', availName: 'cat1_1_c11_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'cat1_1_c12', availName: 'cat1_1_c12_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'cat1_1_c13', availName: 'cat1_1_c13_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'cat1_1_c14', availName: 'cat1_1_c14_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'cat1_1_c15', availName: 'cat1_1_c15_avail' },
          { brand: 'beko', model: 'BM3WFU38200BS', ref: '279 JD', priceName: 'cat1_1_c16', availName: 'cat1_1_c16_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'cat1_1_c17', availName: 'cat1_1_c17_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'cat1_1_c18', availName: 'cat1_1_c18_avail' },
        ],
      },
      {
        id: 'card_cat1_2',
        brand: 'Ariston',
        model: 'NS 823C GG EG',
        existsName: 'cat1_2_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'cat1_2_c0', availName: 'cat1_2_c0_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'cat1_2_c1', availName: 'cat1_2_c1_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'cat1_2_c2', availName: 'cat1_2_c2_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'cat1_2_c3', availName: 'cat1_2_c3_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'cat1_2_c4', availName: 'cat1_2_c4_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'cat1_2_c5', availName: 'cat1_2_c5_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'cat1_2_c6', availName: 'cat1_2_c6_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'cat1_2_c7', availName: 'cat1_2_c7_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'cat1_2_c8', availName: 'cat1_2_c8_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'cat1_2_c9', availName: 'cat1_2_c9_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'cat1_2_c10', availName: 'cat1_2_c10_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'cat1_2_c11', availName: 'cat1_2_c11_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'cat1_2_c12', availName: 'cat1_2_c12_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'cat1_2_c13', availName: 'cat1_2_c13_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'cat1_2_c14', availName: 'cat1_2_c14_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'cat1_2_c15', availName: 'cat1_2_c15_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'cat1_2_c16', availName: 'cat1_2_c16_avail' },
        ],
      },
      {
        id: 'card_cat1_3',
        brand: 'Ariston',
        model: 'NM11 823 SS EG',
        existsName: 'cat1_3_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'cat1_3_c0', availName: 'cat1_3_c0_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'cat1_3_c1', availName: 'cat1_3_c1_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'cat1_3_c2', availName: 'cat1_3_c2_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'cat1_3_c3', availName: 'cat1_3_c3_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'cat1_3_c4', availName: 'cat1_3_c4_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'cat1_3_c5', availName: 'cat1_3_c5_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'cat1_3_c6', availName: 'cat1_3_c6_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'cat1_3_c7', availName: 'cat1_3_c7_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'cat1_3_c8', availName: 'cat1_3_c8_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'cat1_3_c9', availName: 'cat1_3_c9_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'cat1_3_c10', availName: 'cat1_3_c10_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'cat1_3_c11', availName: 'cat1_3_c11_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'cat1_3_c12', availName: 'cat1_3_c12_avail' },
          { brand: 'Ariston', model: 'NM11 823 SS EG', ref: '339 JD', priceName: 'cat1_3_c13', availName: 'cat1_3_c13_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'cat1_3_c14', availName: 'cat1_3_c14_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'cat1_3_c15', availName: 'cat1_3_c15_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'cat1_3_c16', availName: 'cat1_3_c16_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'cat1_3_c17', availName: 'cat1_3_c17_avail' },
        ],
      },
      {
        id: 'card_cat1_4',
        brand: 'beko',
        model: 'B5WFT091400MG',
        existsName: 'cat1_4_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'cat1_4_c0', availName: 'cat1_4_c0_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'cat1_4_c1', availName: 'cat1_4_c1_avail' },
          { brand: 'Media', model: 'MF200W90WB/T', ref: '279 JD', priceName: 'cat1_4_c2', availName: 'cat1_4_c2_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'cat1_4_c3', availName: 'cat1_4_c3_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'cat1_4_c4', availName: 'cat1_4_c4_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'cat1_4_c5', availName: 'cat1_4_c5_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'cat1_4_c6', availName: 'cat1_4_c6_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'cat1_4_c7', availName: 'cat1_4_c7_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'cat1_4_c8', availName: 'cat1_4_c8_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'cat1_4_c9', availName: 'cat1_4_c9_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'cat1_4_c10', availName: 'cat1_4_c10_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'cat1_4_c11', availName: 'cat1_4_c11_avail' },
          { brand: 'beko', model: 'B5WFT091400MG', ref: '329 JD', priceName: 'cat1_4_c12', availName: 'cat1_4_c12_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'cat1_4_c13', availName: 'cat1_4_c13_avail' },
        ],
      },
      {
        id: 'card_cat1_5',
        brand: 'Ariston',
        model: 'NLM11 946 SC A EX',
        existsName: 'cat1_5_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'cat1_5_c0', availName: 'cat1_5_c0_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'cat1_5_c1', availName: 'cat1_5_c1_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'cat1_5_c2', availName: 'cat1_5_c2_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'cat1_5_c3', availName: 'cat1_5_c3_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'cat1_5_c4', availName: 'cat1_5_c4_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'cat1_5_c5', availName: 'cat1_5_c5_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'cat1_5_c6', availName: 'cat1_5_c6_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'cat1_5_c7', availName: 'cat1_5_c7_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'cat1_5_c8', availName: 'cat1_5_c8_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'cat1_5_c9', availName: 'cat1_5_c9_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'cat1_5_c10', availName: 'cat1_5_c10_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'cat1_5_c11', availName: 'cat1_5_c11_avail' },
        ],
      },
      {
        id: 'card_cat1_6',
        brand: 'Ariston',
        model: 'ARWF 09122S MMJ',
        existsName: 'cat1_6_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'cat1_6_c0', availName: 'cat1_6_c0_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'cat1_6_c1', availName: 'cat1_6_c1_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'cat1_6_c2', availName: 'cat1_6_c2_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'cat1_6_c3', availName: 'cat1_6_c3_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'cat1_6_c4', availName: 'cat1_6_c4_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'cat1_6_c5', availName: 'cat1_6_c5_avail' },
          { brand: 'Ariston', model: 'ARWF 09122S MMJ', ref: '399 JD', priceName: 'cat1_6_c6', availName: 'cat1_6_c6_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'cat1_6_c7', availName: 'cat1_6_c7_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'cat1_6_c8', availName: 'cat1_6_c8_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'cat1_6_c9', availName: 'cat1_6_c9_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'cat1_6_c10', availName: 'cat1_6_c10_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'cat1_6_c11', availName: 'cat1_6_c11_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'cat1_6_c12', availName: 'cat1_6_c12_avail' },
        ],
      },
      {
        id: 'card_cat1_7',
        brand: 'beko',
        model: 'B3WFU51042MG',
        existsName: 'cat1_7_exists',
        competitors: [
          { brand: 'Indesit', model: 'BWE 101484X WSSS EU', ref: '599 JD', priceName: 'cat1_7_c0', availName: 'cat1_7_c0_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'cat1_7_c1', availName: 'cat1_7_c1_avail' },
          { brand: 'Whirlpool', model: 'FFD 10449 SBCV GCC', ref: '699 JD', priceName: 'cat1_7_c2', availName: 'cat1_7_c2_avail' },
          { brand: 'Vestel', model: 'WB1014T3DSS', ref: '349 JD', priceName: 'cat1_7_c3', availName: 'cat1_7_c3_avail' },
          { brand: 'Vestel', model: 'WB1014T3DXS', ref: '329 JD', priceName: 'cat1_7_c4', availName: 'cat1_7_c4_avail' },
          { brand: 'beko', model: 'B3WFU51042MG', ref: '429 JD', priceName: 'cat1_7_c5', availName: 'cat1_7_c5_avail' },
          { brand: 'Hisense', model: 'WF3S1043BT (Wifi)', ref: '369 JD', priceName: 'cat1_7_c6', availName: 'cat1_7_c6_avail' },
        ],
      },
      {
        id: 'card_cat1_8',
        brand: 'Ariston',
        model: 'ARWF 10143D MMJ',
        existsName: 'cat1_8_exists',
        competitors: [
          { brand: 'Indesit', model: 'BWE 101484X WSSS EU', ref: '599 JD', priceName: 'cat1_8_c0', availName: 'cat1_8_c0_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'cat1_8_c1', availName: 'cat1_8_c1_avail' },
          { brand: 'Whirlpool', model: 'FFD 10449 SBCV GCC', ref: '699 JD', priceName: 'cat1_8_c2', availName: 'cat1_8_c2_avail' },
          { brand: 'Vestel', model: 'WB1014T3DSS', ref: '349 JD', priceName: 'cat1_8_c3', availName: 'cat1_8_c3_avail' },
          { brand: 'Vestel', model: 'WB1014T3DXS', ref: '329 JD', priceName: 'cat1_8_c4', availName: 'cat1_8_c4_avail' },
          { brand: 'Ariston', model: 'ARWF 10143D MMJ', ref: '429 JD', priceName: 'cat1_8_c5', availName: 'cat1_8_c5_avail' },
          { brand: 'Hisense', model: 'WF3S1043BT (Wifi)', ref: '369 JD', priceName: 'cat1_8_c6', availName: 'cat1_8_c6_avail' },
        ],
      },
      {
        id: 'card_cat1_9',
        brand: 'Ariston',
        model: 'NLLCD 1165 SC AD EX',
        existsName: 'cat1_9_exists',
        competitors: [
          { brand: 'Ariston', model: 'NLLCD 1165 SC AD EX', ref: '599 JD', priceName: 'cat1_9_c0', availName: 'cat1_9_c0_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'cat1_9_c1', availName: 'cat1_9_c1_avail' },
          { brand: 'AEG', model: 'LF8504G6Q', ref: '749 JD', priceName: 'cat1_9_c2', availName: 'cat1_9_c2_avail' },
          { brand: 'Hisense', model: 'WF5S1245BB', ref: '499 JD', priceName: 'cat1_9_c3', availName: 'cat1_9_c3_avail' },
          { brand: 'Hisense', model: 'WFQA1214EVJMT-JO', ref: '419 JD', priceName: 'cat1_9_c4', availName: 'cat1_9_c4_avail' },
          { brand: 'Vestel', model: 'WB1214T3DXS-JO', ref: '379 JD', priceName: 'cat1_9_c5', availName: 'cat1_9_c5_avail' },
          { brand: 'Hisense', model: 'WF3S1243BT', ref: '449 JD', priceName: 'cat1_9_c6', availName: 'cat1_9_c6_avail' },
        ],
      },
      {
        id: 'card_cat1_10',
        brand: 'beko',
        model: 'BM3WFT412400BS',
        existsName: 'cat1_10_exists',
        competitors: [
          { brand: 'Ariston', model: 'NLLCD 1165 SC AD EX', ref: '599 JD', priceName: 'cat1_10_c0', availName: 'cat1_10_c0_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'cat1_10_c1', availName: 'cat1_10_c1_avail' },
          { brand: 'AEG', model: 'LF8504G6Q', ref: '749 JD', priceName: 'cat1_10_c2', availName: 'cat1_10_c2_avail' },
          { brand: 'Hisense', model: 'WF5S1245BB', ref: '499 JD', priceName: 'cat1_10_c3', availName: 'cat1_10_c3_avail' },
          { brand: 'Hisense', model: 'WFQA1214EVJMT-JO', ref: '419 JD', priceName: 'cat1_10_c4', availName: 'cat1_10_c4_avail' },
          { brand: 'Vestel', model: 'WB1214T3DXS-JO', ref: '379 JD', priceName: 'cat1_10_c5', availName: 'cat1_10_c5_avail' },
          { brand: 'beko', model: 'BM3WFT412400BS', ref: '499 JD', priceName: 'cat1_10_c6', availName: 'cat1_10_c6_avail' },
          { brand: 'Hisense', model: 'WF3S1243BT', ref: '449 JD', priceName: 'cat1_10_c7', availName: 'cat1_10_c7_avail' },
        ],
      },
    ],
  },
  {
    icon: '♨️',
    title: 'المجففات',
    sub: 'Dryers',
    products: [
      {
        id: 'card_cat2_0',
        brand: 'beko',
        model: 'B5T68254MG',
        existsName: 'cat2_0_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M10 8X1S EX', ref: '—', priceName: 'cat2_0_c0', availName: 'cat2_0_c0_avail' },
          { brand: 'Whirlpool', model: 'FFT M11 8X 1SBS', ref: '575 JD', priceName: 'cat2_0_c1', availName: 'cat2_0_c1_avail' },
          { brand: 'Whirlpool', model: 'FFT M11 81S EX', ref: '575 JD', priceName: 'cat2_0_c2', availName: 'cat2_0_c2_avail' },
          { brand: 'Samsung', model: 'DV80TA020AX/EU', ref: '509 JD', priceName: 'cat2_0_c3', availName: 'cat2_0_c3_avail' },
          { brand: 'Vestel', model: 'TDH8SGT3DX', ref: '389 JD', priceName: 'cat2_0_c4', availName: 'cat2_0_c4_avail' },
        ],
      },
      {
        id: 'card_cat2_1',
        brand: 'beko',
        model: 'B5T69254MG',
        existsName: 'cat2_1_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M11 9X1SXB EX', ref: '559 JD', priceName: 'cat2_1_c0', availName: 'cat2_1_c0_avail' },
          { brand: 'Conti', model: 'TD-HP92-S', ref: '349 JD', priceName: 'cat2_1_c1', availName: 'cat2_1_c1_avail' },
          { brand: 'Whirlpool', model: 'FFT D 9X 3SK EX', ref: '699 JD', priceName: 'cat2_1_c2', availName: 'cat2_1_c2_avail' },
          { brand: 'Samsung', model: 'DV90T6240LX/FH', ref: '549 JD', priceName: 'cat2_1_c3', availName: 'cat2_1_c3_avail' },
          { brand: 'AEG', model: 'EW8H1966TBS', ref: '799 JD', priceName: 'cat2_1_c4', availName: 'cat2_1_c4_avail' },
          { brand: 'Samsung', model: 'DV90BB7440GBFH (Bespoke)', ref: '719 JD', priceName: 'cat2_1_c5', availName: 'cat2_1_c5_avail' },
          { brand: 'Samsung', model: 'DV90T7240BX/FH', ref: '549 JD', priceName: 'cat2_1_c6', availName: 'cat2_1_c6_avail' },
          { brand: 'Vestel', model: 'TDH9SGT3DX', ref: '449 JD', priceName: 'cat2_1_c7', availName: 'cat2_1_c7_avail' },
          { brand: 'Hisense', model: 'DH3S902BT', ref: '399 JD', priceName: 'cat2_1_c8', availName: 'cat2_1_c8_avail' },
          { brand: 'Samsung', model: 'DV90DG52A0ABEU', ref: '499 JD', priceName: 'cat2_1_c9', availName: 'cat2_1_c9_avail' },
        ],
      },
      {
        id: 'card_cat2_2',
        brand: 'Ariston',
        model: 'ARDH 092S 25 MMJ',
        existsName: 'cat2_2_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M11 9X1SXB EX', ref: '559 JD', priceName: 'cat2_2_c0', availName: 'cat2_2_c0_avail' },
          { brand: 'Conti', model: 'TD-HP92-S', ref: '349 JD', priceName: 'cat2_2_c1', availName: 'cat2_2_c1_avail' },
          { brand: 'Whirlpool', model: 'FFT D 9X 3SK EX', ref: '699 JD', priceName: 'cat2_2_c2', availName: 'cat2_2_c2_avail' },
          { brand: 'Samsung', model: 'DV90T6240LX/FH', ref: '549 JD', priceName: 'cat2_2_c3', availName: 'cat2_2_c3_avail' },
          { brand: 'AEG', model: 'EW8H1966TBS', ref: '799 JD', priceName: 'cat2_2_c4', availName: 'cat2_2_c4_avail' },
          { brand: 'Samsung', model: 'DV90BB7440GBFH (Bespoke)', ref: '719 JD', priceName: 'cat2_2_c5', availName: 'cat2_2_c5_avail' },
          { brand: 'Samsung', model: 'DV90T7240BX/FH', ref: '549 JD', priceName: 'cat2_2_c6', availName: 'cat2_2_c6_avail' },
          { brand: 'Vestel', model: 'TDH9SGT3DX', ref: '449 JD', priceName: 'cat2_2_c7', availName: 'cat2_2_c7_avail' },
          { brand: 'Hisense', model: 'DH3S902BT', ref: '399 JD', priceName: 'cat2_2_c8', availName: 'cat2_2_c8_avail' },
          { brand: 'Samsung', model: 'DV90DG52A0ABEU', ref: '499 JD', priceName: 'cat2_2_c9', availName: 'cat2_2_c9_avail' },
        ],
      },
      {
        id: 'card_cat2_3',
        brand: 'Ariston',
        model: 'ARDH 103D MMJ',
        existsName: 'cat2_3_exists',
        competitors: [
          { brand: 'Hisense', model: 'DH5S102BB', ref: '499 JD', priceName: 'cat2_3_c0', availName: 'cat2_3_c0_avail' },
        ],
      },
      {
        id: 'card_cat2_4',
        brand: 'beko',
        model: 'BM3T12NXS',
        existsName: 'cat2_4_exists',
        competitors: [
          { brand: 'Hisense', model: 'DH5S102BB', ref: '499 JD', priceName: 'cat2_4_c0', availName: 'cat2_4_c0_avail' },
        ],
      },
    ],
  },
  {
    icon: '🔄',
    title: 'غسالة + مجفف',
    sub: 'Washer & Dryer',
    products: [
      {
        id: 'card_cat3_0',
        brand: 'beko',
        model: 'B3DFT51042MG',
        existsName: 'cat3_0_exists',
        competitors: [
          { brand: 'Samsung', model: 'WD80T554DBN/FH', ref: '559 JD', priceName: 'cat3_0_c0', availName: 'cat3_0_c0_avail' },
          { brand: 'LG', model: 'F4V9VCP2E.SBLPEL', ref: '619 JD', priceName: 'cat3_0_c1', availName: 'cat3_0_c1_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DX', ref: '549 JD', priceName: 'cat3_0_c2', availName: 'cat3_0_c2_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DS', ref: '549 JD', priceName: 'cat3_0_c3', availName: 'cat3_0_c3_avail' },
          { brand: 'Indesit', model: 'XWDE 961480X S EU', ref: '649 JD', priceName: 'cat3_0_c4', availName: 'cat3_0_c4_avail' },
          { brand: 'Indesit', model: 'BDE 964 SSV GCC', ref: '700 JD', priceName: 'cat3_0_c5', availName: 'cat3_0_c5_avail' },
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'cat3_0_c6', availName: 'cat3_0_c6_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'cat3_0_c7', availName: 'cat3_0_c7_avail' },
        ],
      },
      {
        id: 'card_cat3_1',
        brand: 'Ariston',
        model: 'NDB 96 SS EX',
        existsName: 'cat3_1_exists',
        competitors: [
          { brand: 'Samsung', model: 'WD80T554DBN/FH', ref: '559 JD', priceName: 'cat3_1_c0', availName: 'cat3_1_c0_avail' },
          { brand: 'LG', model: 'F4V9VCP2E.SBLPEL', ref: '619 JD', priceName: 'cat3_1_c1', availName: 'cat3_1_c1_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DX', ref: '549 JD', priceName: 'cat3_1_c2', availName: 'cat3_1_c2_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DS', ref: '549 JD', priceName: 'cat3_1_c3', availName: 'cat3_1_c3_avail' },
          { brand: 'Indesit', model: 'XWDE 961480X S EU', ref: '649 JD', priceName: 'cat3_1_c4', availName: 'cat3_1_c4_avail' },
          { brand: 'Indesit', model: 'BDE 964 SSV GCC', ref: '700 JD', priceName: 'cat3_1_c5', availName: 'cat3_1_c5_avail' },
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'cat3_1_c6', availName: 'cat3_1_c6_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'cat3_1_c7', availName: 'cat3_1_c7_avail' },
        ],
      },
      {
        id: 'card_cat3_2',
        brand: 'Ariston',
        model: 'NDD 1170 SSA EX',
        existsName: 'cat3_2_exists',
        competitors: [
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'cat3_2_c0', availName: 'cat3_2_c0_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'cat3_2_c1', availName: 'cat3_2_c1_avail' },
          { brand: 'Midea', model: 'MF200D120WB', ref: '499 JD', priceName: 'cat3_2_c2', availName: 'cat3_2_c2_avail' },
        ],
      },
    ],
  },
  {
    icon: '🍽️',
    title: 'غسالة الجلي',
    sub: 'Dishwashers',
    products: [
      {
        id: 'card_cat4_0',
        brand: 'beko',
        model: 'DVN 05321S-JO',
        existsName: 'cat4_0_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5050FS', ref: '—', priceName: 'cat4_0_c0', availName: 'cat4_0_c0_avail' },
          { brand: 'Whirlpool', model: 'WFE 2B19 N X', ref: '—', priceName: 'cat4_0_c1', availName: 'cat4_0_c1_avail' },
          { brand: 'Ariston', model: 'LFC 2B19 X', ref: '—', priceName: 'cat4_0_c2', availName: 'cat4_0_c2_avail' },
          { brand: 'Hisense', model: 'H13DESS', ref: '—', priceName: 'cat4_0_c3', availName: 'cat4_0_c3_avail' },
        ],
      },
      {
        id: 'card_cat4_1',
        brand: 'beko',
        model: 'BDFN16422S',
        existsName: 'cat4_1_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-MB612-SS2', ref: '—', priceName: 'cat4_1_c0', availName: 'cat4_1_c0_avail' },
          { brand: 'Conti', model: 'DW-71B23-SL', ref: '183 JD', priceName: 'cat4_1_c1', availName: 'cat4_1_c1_avail' },
        ],
      },
      {
        id: 'card_cat4_2',
        brand: 'beko',
        model: 'BDFN16422B',
        existsName: 'cat4_2_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-V615-BK3', ref: '—', priceName: 'cat4_2_c0', availName: 'cat4_2_c0_avail' },
          { brand: 'Conti', model: 'DW-6L-23-BK', ref: '—', priceName: 'cat4_2_c1', availName: 'cat4_2_c1_avail' },
          { brand: 'Vestel', model: 'DWFA1E6B0X', ref: '202 JD', priceName: 'cat4_2_c2', availName: 'cat4_2_c2_avail' },
        ],
      },
      {
        id: 'card_cat4_3',
        brand: 'beko',
        model: 'BDFN36422XQ',
        existsName: 'cat4_3_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-MB612-SS2', ref: '—', priceName: 'cat4_3_c0', availName: 'cat4_3_c0_avail' },
          { brand: 'Indesit', model: 'DFC 2B+16 AC X', ref: '—', priceName: 'cat4_3_c1', availName: 'cat4_3_c1_avail' },
          { brand: 'Conti', model: 'DW-71B23-SL', ref: '183 JD', priceName: 'cat4_3_c2', availName: 'cat4_3_c2_avail' },
        ],
      },
      {
        id: 'card_cat4_4',
        brand: 'Ariston',
        model: 'LFC 3C26 W X',
        existsName: 'cat4_4_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'cat4_4_c0', availName: 'cat4_4_c0_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'cat4_4_c1', availName: 'cat4_4_c1_avail' },
          { brand: 'Vestel', model: 'DWFA328B1X', ref: '255 JD', priceName: 'cat4_4_c2', availName: 'cat4_4_c2_avail' },
          { brand: 'Hisense', model: 'HS622E91X', ref: '228 JD', priceName: 'cat4_4_c3', availName: 'cat4_4_c3_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'cat4_4_c4', availName: 'cat4_4_c4_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'cat4_4_c5', availName: 'cat4_4_c5_avail' },
          { brand: 'AEG', model: 'FFB73727PM', ref: '—', priceName: 'cat4_4_c6', availName: 'cat4_4_c6_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'cat4_4_c7', availName: 'cat4_4_c7_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'cat4_4_c8', availName: 'cat4_4_c8_avail' },
          { brand: 'Electrolux', model: 'ESS47311SX', ref: '—', priceName: 'cat4_4_c9', availName: 'cat4_4_c9_avail' },
          { brand: 'Vestel', model: 'DWFA358B1X', ref: '—', priceName: 'cat4_4_c10', availName: 'cat4_4_c10_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'cat4_4_c11', availName: 'cat4_4_c11_avail' },
        ],
      },
      {
        id: 'card_cat4_5',
        brand: 'beko',
        model: 'BDEN38523XQ',
        existsName: 'cat4_5_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'cat4_5_c0', availName: 'cat4_5_c0_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'cat4_5_c1', availName: 'cat4_5_c1_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'cat4_5_c2', availName: 'cat4_5_c2_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'cat4_5_c3', availName: 'cat4_5_c3_avail' },
          { brand: 'Vestel', model: 'DWFA328B1X', ref: '255 JD', priceName: 'cat4_5_c4', availName: 'cat4_5_c4_avail' },
          { brand: 'Hisense', model: 'HS622E91X', ref: '228 JD', priceName: 'cat4_5_c5', availName: 'cat4_5_c5_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'cat4_5_c6', availName: 'cat4_5_c6_avail' },
          { brand: 'Electrolux', model: 'ESS47311SX', ref: '—', priceName: 'cat4_5_c7', availName: 'cat4_5_c7_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'cat4_5_c8', availName: 'cat4_5_c8_avail' },
          { brand: 'AEG', model: 'FFB73727PM', ref: '—', priceName: 'cat4_5_c9', availName: 'cat4_5_c9_avail' },
          { brand: 'Vestel', model: 'DWFA358B1X', ref: '—', priceName: 'cat4_5_c10', availName: 'cat4_5_c10_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'cat4_5_c11', availName: 'cat4_5_c11_avail' },
        ],
      },
      {
        id: 'card_cat4_6',
        brand: 'beko',
        model: 'BDEN38523MG',
        existsName: 'cat4_6_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'cat4_6_c0', availName: 'cat4_6_c0_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'cat4_6_c1', availName: 'cat4_6_c1_avail' },
          { brand: 'Conti', model: 'DW-81L33-DIX', ref: '—', priceName: 'cat4_6_c2', availName: 'cat4_6_c2_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'cat4_6_c3', availName: 'cat4_6_c3_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'cat4_6_c4', availName: 'cat4_6_c4_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'cat4_6_c5', availName: 'cat4_6_c5_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'cat4_6_c6', availName: 'cat4_6_c6_avail' },
          { brand: 'AEG', model: 'FFB83836PM', ref: '—', priceName: 'cat4_6_c7', availName: 'cat4_6_c7_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'cat4_6_c8', availName: 'cat4_6_c8_avail' },
        ],
      },
      {
        id: 'card_cat4_7',
        brand: 'Ariston',
        model: 'LFC 3C33 WF X',
        existsName: 'cat4_7_exists',
        competitors: [
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'cat4_7_c0', availName: 'cat4_7_c0_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'cat4_7_c1', availName: 'cat4_7_c1_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'cat4_7_c2', availName: 'cat4_7_c2_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'cat4_7_c3', availName: 'cat4_7_c3_avail' },
          { brand: 'AEG', model: 'FFB83836PM', ref: '—', priceName: 'cat4_7_c4', availName: 'cat4_7_c4_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'cat4_7_c5', availName: 'cat4_7_c5_avail' },
        ],
      },
      {
        id: 'card_cat4_8',
        brand: 'Ariston',
        model: 'LFO 3P31 WL',
        existsName: 'cat4_8_exists',
        competitors: [
          { brand: 'LG', model: 'DFB512FW.ABWPELF Direct Drive', ref: '370 JD', priceName: 'cat4_8_c0', availName: 'cat4_8_c0_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'cat4_8_c1', availName: 'cat4_8_c1_avail' },
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'cat4_8_c2', availName: 'cat4_8_c2_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'cat4_8_c3', availName: 'cat4_8_c3_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'cat4_8_c4', availName: 'cat4_8_c4_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'cat4_8_c5', availName: 'cat4_8_c5_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'cat4_8_c6', availName: 'cat4_8_c6_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'cat4_8_c7', availName: 'cat4_8_c7_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'cat4_8_c8', availName: 'cat4_8_c8_avail' },
        ],
      },
      {
        id: 'card_cat4_9',
        brand: 'Ariston',
        model: 'LFO 3P31 WL X',
        existsName: 'cat4_9_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'cat4_9_c0', availName: 'cat4_9_c0_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'cat4_9_c1', availName: 'cat4_9_c1_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'cat4_9_c2', availName: 'cat4_9_c2_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'cat4_9_c3', availName: 'cat4_9_c3_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'cat4_9_c4', availName: 'cat4_9_c4_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'cat4_9_c5', availName: 'cat4_9_c5_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'cat4_9_c6', availName: 'cat4_9_c6_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'cat4_9_c7', availName: 'cat4_9_c7_avail' },
        ],
      },
      {
        id: 'card_cat4_10',
        brand: 'Ariston',
        model: 'LFP 5P31 WLT X',
        existsName: 'cat4_10_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'cat4_10_c0', availName: 'cat4_10_c0_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'cat4_10_c1', availName: 'cat4_10_c1_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'cat4_10_c2', availName: 'cat4_10_c2_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'cat4_10_c3', availName: 'cat4_10_c3_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'cat4_10_c4', availName: 'cat4_10_c4_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'cat4_10_c5', availName: 'cat4_10_c5_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'cat4_10_c6', availName: 'cat4_10_c6_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'cat4_10_c7', availName: 'cat4_10_c7_avail' },
        ],
      },
      {
        id: 'card_cat4_11',
        brand: 'beko',
        model: 'BDFN36651XC',
        existsName: 'cat4_11_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'cat4_11_c0', availName: 'cat4_11_c0_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'cat4_11_c1', availName: 'cat4_11_c1_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'cat4_11_c2', availName: 'cat4_11_c2_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'cat4_11_c3', availName: 'cat4_11_c3_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'cat4_11_c4', availName: 'cat4_11_c4_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'cat4_11_c5', availName: 'cat4_11_c5_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'cat4_11_c6', availName: 'cat4_11_c6_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'cat4_11_c7', availName: 'cat4_11_c7_avail' },
        ],
      },
      {
        id: 'card_cat4_12',
        brand: 'beko',
        model: 'BDFN39410XC',
        existsName: 'cat4_12_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'cat4_12_c0', availName: 'cat4_12_c0_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'cat4_12_c1', availName: 'cat4_12_c1_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'cat4_12_c2', availName: 'cat4_12_c2_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'cat4_12_c3', availName: 'cat4_12_c3_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'cat4_12_c4', availName: 'cat4_12_c4_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'cat4_12_c5', availName: 'cat4_12_c5_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'cat4_12_c6', availName: 'cat4_12_c6_avail' },
        ],
      },
      {
        id: 'card_cat4_13',
        brand: 'Ariston',
        model: 'LIC 3B+26',
        existsName: 'cat4_13_exists',
        competitors: [
          { brand: 'Whirlpool', model: 'WIE 2B19 N UK', ref: '—', priceName: 'cat4_13_c0', availName: 'cat4_13_c0_avail' },
          { brand: 'Whirlpool', model: 'WBC 3C34 PF X', ref: '—', priceName: 'cat4_13_c1', availName: 'cat4_13_c1_avail' },
        ],
      },
    ],
  },
  {
    icon: '❄️',
    title: 'الفريزر القائم',
    sub: 'Upright Freezers',
    products: [
      {
        id: 'card_cat5_0',
        brand: 'beko',
        model: 'RFSA240M23X',
        existsName: 'cat5_0_exists',
        competitors: [
          { brand: 'Midea', model: 'MDRU229FZF01', ref: '—', priceName: 'cat5_0_c0', availName: 'cat5_0_c0_avail' },
          { brand: 'Midea', model: 'MDRU229FZF02', ref: '180 JD', priceName: 'cat5_0_c1', availName: 'cat5_0_c1_avail' },
          { brand: 'Vestel', model: 'RN270FR3EI-BG', ref: '266 JD', priceName: 'cat5_0_c2', availName: 'cat5_0_c2_avail' },
          { brand: 'Vestel', model: 'RN360FR3EI-X', ref: '275 JD', priceName: 'cat5_0_c3', availName: 'cat5_0_c3_avail' },
        ],
      },
      {
        id: 'card_cat5_1',
        brand: 'beko',
        model: 'RFNM200E20W',
        existsName: 'cat5_1_exists',
        competitors: [
          { brand: 'Ignis', model: 'CSTNF231 (Three Years Warranty)', ref: '—', priceName: 'cat5_1_c0', availName: 'cat5_1_c0_avail' },
          { brand: 'Vestel', model: 'RN270FR3EI-BG', ref: '266 JD', priceName: 'cat5_1_c1', availName: 'cat5_1_c1_avail' },
          { brand: 'Tekmaz', model: 'NAS-6DS', ref: '315 JD', priceName: 'cat5_1_c2', availName: 'cat5_1_c2_avail' },
        ],
      },
      {
        id: 'card_cat5_2',
        brand: 'beko',
        model: 'RFNE340L31XB',
        existsName: 'cat5_2_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN360FR3EI-X', ref: '275 JD', priceName: 'cat5_2_c0', availName: 'cat5_2_c0_avail' },
          { brand: 'Newton', model: '355Usm  (With Screen)', ref: '—', priceName: 'cat5_2_c1', availName: 'cat5_2_c1_avail' },
          { brand: 'Newton', model: '466Usm  (With Screen)', ref: '—', priceName: 'cat5_2_c2', availName: 'cat5_2_c2_avail' },
          { brand: 'Ignis', model: 'CST381S (Two Years Warranty)', ref: '—', priceName: 'cat5_2_c3', availName: 'cat5_2_c3_avail' },
          { brand: 'Hisense', model: 'FV356N4ASU With 10 Years Compressor Warranty (With Screen)', ref: '365 JD', priceName: 'cat5_2_c4', availName: 'cat5_2_c4_avail' },
          { brand: 'Indesit', model: 'UI6 F1T S', ref: '—', priceName: 'cat5_2_c5', availName: 'cat5_2_c5_avail' },
          { brand: 'Indesit', model: 'UI8 F1D X (With Screen)', ref: '—', priceName: 'cat5_2_c6', availName: 'cat5_2_c6_avail' },
          { brand: 'Samsung', model: 'RZ32M71207F/SG With 20 Years Compressor Warranty (With Screen)', ref: '—', priceName: 'cat5_2_c7', availName: 'cat5_2_c7_avail' },
        ],
      },
      {
        id: 'card_cat5_3',
        brand: 'beko',
        model: 'RFNE451XB Inverter Compressor with 10 Years Warranty (With Screen)',
        existsName: 'cat5_3_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN440FR3F-DX  (With Screen)', ref: '380 JD', priceName: 'cat5_3_c0', availName: 'cat5_3_c0_avail' },
          { brand: 'Vestel', model: 'RN440FR3F-X  (With Screen)', ref: '380 JD', priceName: 'cat5_3_c1', availName: 'cat5_3_c1_avail' },
          { brand: 'Benkon', model: 'FR-BN371S  (With Screen)', ref: '—', priceName: 'cat5_3_c2', availName: 'cat5_3_c2_avail' },
          { brand: 'Blumatic', model: 'BUF300X', ref: '—', priceName: 'cat5_3_c3', availName: 'cat5_3_c3_avail' },
          { brand: 'Sharp', model: 'SJ-SFR415-HS2/3', ref: '—', priceName: 'cat5_3_c4', availName: 'cat5_3_c4_avail' },
          { brand: 'Samsung', model: 'RZ32M71207F/SG With 20 Years Compressor Warranty (With Screen)', ref: '—', priceName: 'cat5_3_c5', availName: 'cat5_3_c5_avail' },
        ],
      },
      {
        id: 'card_cat5_4',
        brand: 'beko',
        model: 'RFNE448E35XP Inverter Compressor with 10 Years Warranty (With Screen)',
        existsName: 'cat5_4_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN600FR4F-X  (With Screen)', ref: '506 JD', priceName: 'cat5_4_c0', availName: 'cat5_4_c0_avail' },
        ],
      },
    ],
  },
];