export const FORM_SECTIONS = [
  {
    icon: '🧊',
    title: 'الثلاجات',
    sub: 'Refrigerators',
    products: [
      {
        id: 'card_refrigerators_beko_rdng491m20',
        brand: 'beko',
        model: 'RDNG491M20SXB (Egypt)  RDNG491M20BP (Egypt)',
        existsName: 'beko_rdng491m20_exists',
        competitors: [
          { brand: 'Bosch', model: 'KDN43VL2M8', ref: '450 JD', priceName: 'bosch_kdn43vl2m8_price', availName: 'bosch_kdn43vl2m8_avail' },
          { brand: 'Toshiba', model: 'GR-RT468WE-PMF(37)', ref: '329 JD', priceName: 'toshiba_gr_rt468we_pmf37_price', availName: 'toshiba_gr_rt468we_pmf37_avail' },
          { brand: 'Midea', model: 'MDRT489MTE46', ref: '299 JD', priceName: 'midea_mdrt489mte46_price', availName: 'midea_mdrt489mte46_avail' },
          { brand: 'Hisense', model: 'RT488N4ASU', ref: '369 JD', priceName: 'hisense_rt488n4asu_price', availName: 'hisense_rt488n4asu_avail' },
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'samsung_rt38cg6000s9jo_price', availName: 'samsung_rt38cg6000s9jo_avail' },
          { brand: 'Sharp', model: 'SJ-58C', ref: '329 JD', priceName: 'sharp_sj58c_price', availName: 'sharp_sj58c_avail' },
          { brand: 'beko', model: 'RDNG491M20BP', ref: '329 JD', priceName: 'beko_rdng491m20bp_price', availName: 'beko_rdng491m20bp_avail' },
          { brand: 'beko', model: 'RDNG491M20SXB', ref: '329 JD', priceName: 'beko_rdng491m20sxb_price', availName: 'beko_rdng491m20sxb_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_rdng551m20',
        brand: 'beko',
        model: 'RDNG551M20TSX (Egypt)  RDNG551M20TXBR (Egypt)',
        existsName: 'beko_rdng551m20_exists',
        competitors: [
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'samsung_rt38cg6000s9jo_price', availName: 'samsung_rt38cg6000s9jo_avail' },
          { brand: 'Toshiba', model: 'GR-RT559WE-PMF(37)', ref: '369 JD', priceName: 'toshiba_gr_rt559we_pmf37_price', availName: 'toshiba_gr_rt559we_pmf37_avail' },
          { brand: 'Midea', model: 'MDRT580MTE46D', ref: '349 JD', priceName: 'midea_mdrt580mte46d_price', availName: 'midea_mdrt580mte46d_avail' },
          { brand: 'Sharp', model: 'SJ-58C', ref: '329 JD', priceName: 'sharp_sj58c_price', availName: 'sharp_sj58c_avail' },
          { brand: 'Samsung', model: 'RT47CG6002S9JO', ref: '499 JD', priceName: 'samsung_rt47cg6002s9jo_price', availName: 'samsung_rt47cg6002s9jo_avail' },
          { brand: 'beko', model: 'RDNG551M20TSX', ref: '369 JD', priceName: 'beko_rdng551m20tsx_price', availName: 'beko_rdng551m20tsx_avail' },
          { brand: 'beko', model: 'RDNG551M20TXBR', ref: '379 JD', priceName: 'beko_rdng551m20txbr_price', availName: 'beko_rdng551m20txbr_avail' },
        ],
      },
      {
        id: 'card_refrigerators_ariston_art70f1452xle',
        brand: 'Ariston',
        model: 'ART70 F1452 XLE',
        existsName: 'ariston_art70f1452xle_exists',
        competitors: [
          { brand: 'Samsung', model: 'RT38CG6000S9JO', ref: '369 JD', priceName: 'samsung_rt38cg6000s9jo_price', availName: 'samsung_rt38cg6000s9jo_avail' },
          { brand: 'Ariston', model: 'ART70 F1452 XLE', ref: '529 JD', priceName: 'ariston_art70f1452xle_price', availName: 'ariston_art70f1452xle_avail' },
          { brand: 'Toshiba', model: 'GR-RT559WE-PMF(37)', ref: '369 JD', priceName: 'toshiba_gr_rt559we_pmf37_price', availName: 'toshiba_gr_rt559we_pmf37_avail' },
          { brand: 'Whirlpool', model: 'W7TI 8711 NFX EX', ref: '549 JD', priceName: 'whirlpool_w7ti8711nfxex_price', availName: 'whirlpool_w7ti8711nfxex_avail' },
          { brand: 'Electrolux', model: 'ETB4600B-A', ref: '699 JD', priceName: 'electrolux_etb4600ba_price', availName: 'electrolux_etb4600ba_avail' },
          { brand: 'Indesit', model: 'I7TM 8111 NFX UK EX', ref: '549 JD', priceName: 'indesit_i7tm8111nfxukex_price', availName: 'indesit_i7tm8111nfxukex_avail' },
          { brand: 'LG', model: 'GLM-592LI.DPZPELF', ref: '499 JD', priceName: 'lg_glm592li_price', availName: 'lg_glm592li_avail' },
          { brand: 'Bosch', model: 'KDN55NL20U', ref: '600 JD', priceName: 'bosch_kdn55nl20u_price', availName: 'bosch_kdn55nl20u_avail' },
          { brand: 'LG', model: 'GNB-682FVFP.APYPELF', ref: '569 JD', priceName: 'lg_gnb682fvfp_price', availName: 'lg_gnb682fvfp_avail' },
          { brand: 'Samsung', model: 'RT47CG6002S9JO', ref: '499 JD', priceName: 'samsung_rt47cg6002s9jo_price', availName: 'samsung_rt47cg6002s9jo_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_b3rdne66hxp',
        brand: 'beko',
        model: 'B3RDNE66HXP',
        existsName: 'beko_b3rdne66hxp_exists',
        competitors: [
          { brand: 'Hisense', model: 'RT599N4ASU', ref: '399 JD', priceName: 'hisense_rt599n4asu_price', availName: 'hisense_rt599n4asu_avail' },
          { brand: 'LG', model: 'GNM-732HLI.APZPELF', ref: '799 JD', priceName: 'lg_gnm732hli_price', availName: 'lg_gnm732hli_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'vestel_rm750tf3fx_price', availName: 'vestel_rm750tf3fx_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'vestel_rm750tf3fdx_price', availName: 'vestel_rm750tf3fdx_avail' },
          { brand: 'Hitachi', model: 'HRTN8565DF-BSL (New)', ref: '777 JD', priceName: 'hitachi_hrtn8565dfbsl_price', availName: 'hitachi_hrtn8565dfbsl_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'samsung_rt53k6000s8jo_old_price', availName: 'samsung_rt53k6000s8jo_old_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'samsung_rt53dg7a60s9jo_new_price', availName: 'samsung_rt53dg7a60s9jo_new_avail' },
          { brand: 'Sharp', model: 'SJ-SE72D', ref: '799 JD', priceName: 'sharp_sjse72d_price', availName: 'sharp_sjse72d_avail' },
          { brand: 'Bosch', model: 'KDN76XL30U', ref: '790 JD', priceName: 'bosch_kdn76xl30u_price', availName: 'bosch_kdn76xl30u_avail' },
          { brand: 'beko', model: 'B3RDNE66HXP', ref: '679 JD', priceName: 'beko_b3rdne66hxp_price', availName: 'beko_b3rdne66hxp_avail' },
          { brand: 'Hisense', model: 'RT729N4ASU', ref: '589 JD', priceName: 'hisense_rt729n4asu_price', availName: 'hisense_rt729n4asu_avail' },
        ],
      },
      {
        id: 'card_refrigerators_ariston_art78f6593xlna',
        brand: 'Ariston',
        model: 'ART78 F6593 XLNA',
        existsName: 'ariston_art78f6593xlna_exists',
        competitors: [
          { brand: 'LG', model: 'GNM-732HLI.APZPELF', ref: '799 JD', priceName: 'lg_gnm732hli_price', availName: 'lg_gnm732hli_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'vestel_rm750tf3fx_price', availName: 'vestel_rm750tf3fx_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'vestel_rm750tf3fdx_price', availName: 'vestel_rm750tf3fdx_avail' },
          { brand: 'Hitachi', model: 'HRTN8565DF-BSL (New)', ref: '777 JD', priceName: 'hitachi_hrtn8565dfbsl_price', availName: 'hitachi_hrtn8565dfbsl_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'samsung_rt53k6000s8jo_old_price', availName: 'samsung_rt53k6000s8jo_old_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'samsung_rt53dg7a60s9jo_new_price', availName: 'samsung_rt53dg7a60s9jo_new_avail' },
          { brand: 'Sharp', model: 'SJ-SE72D', ref: '799 JD', priceName: 'sharp_sjse72d_price', availName: 'sharp_sjse72d_avail' },
          { brand: 'Bosch', model: 'KDN76XL30U', ref: '790 JD', priceName: 'bosch_kdn76xl30u_price', availName: 'bosch_kdn76xl30u_avail' },
          { brand: 'Ariston', model: 'ART78 F6593 XLNA', ref: '849 JD', priceName: 'ariston_art78f6593xlna_price', availName: 'ariston_art78f6593xlna_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_dn168121xb',
        brand: 'beko',
        model: 'DN168121XB',
        existsName: 'beko_dn168121xb_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM750TF3F-X', ref: '499 JD', priceName: 'vestel_rm750tf3fx_price', availName: 'vestel_rm750tf3fx_avail' },
          { brand: 'Vestel', model: 'RM750TF3F-DX', ref: '569 JD', priceName: 'vestel_rm750tf3fdx_price', availName: 'vestel_rm750tf3fdx_avail' },
          { brand: 'Samsung', model: 'RT53K6000S8/JO (Old)', ref: '649 JD', priceName: 'samsung_rt53k6000s8jo_old_price', availName: 'samsung_rt53k6000s8jo_old_avail' },
          { brand: 'Samsung', model: 'RT53DG7A60S9JO (New)', ref: '669 JD', priceName: 'samsung_rt53dg7a60s9jo_new_price', availName: 'samsung_rt53dg7a60s9jo_new_avail' },
          { brand: 'Hisense', model: 'RT729N4ASU', ref: '589 JD', priceName: 'hisense_rt729n4asu_price', availName: 'hisense_rt729n4asu_avail' },
          { brand: 'beko', model: 'DN168121XB', ref: '649 JD', priceName: 'beko_dn168121xb_price', availName: 'beko_dn168121xb_avail' },
          { brand: 'Whirlpool', model: 'WTMF 836633 XNA', ref: '900 JD', priceName: 'whirlpool_wtmf836633xna_price', availName: 'whirlpool_wtmf836633xna_avail' },
          { brand: 'Indesit', model: 'I84TE 31 X EX', ref: '899 JD', priceName: 'indesit_i84te31xex_price', availName: 'indesit_i84te31xex_avail' },
          { brand: 'Sharp', model: 'SJ-GP77D-SL', ref: '999 JD', priceName: 'sharp_sjgp77dsl_price', availName: 'sharp_sjgp77dsl_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_rdne710e40sxp',
        brand: 'beko',
        model: 'RDNE710E40SXP  RDNE710E40SXBR',
        existsName: 'beko_rdne710e40sxp_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM850TF4E-XCL', ref: '599 JD', priceName: 'vestel_rm850tf4excl_price', availName: 'vestel_rm850tf4excl_avail' },
          { brand: 'Vestel', model: 'RM850TF4E-DXCL', ref: '609 JD', priceName: 'vestel_rm850tf4edxcl_price', availName: 'vestel_rm850tf4edxcl_avail' },
          { brand: 'Samsung', model: 'RT58K7000S8/JO', ref: '769 JD', priceName: 'samsung_rt58k7000s8jo_price', availName: 'samsung_rt58k7000s8jo_avail' },
          { brand: 'Sharp', model: 'SJ-GP77D-SL', ref: '999 JD', priceName: 'sharp_sjgp77dsl_price', availName: 'sharp_sjgp77dsl_avail' },
          { brand: 'LG', model: 'GRM-852HLI.APZPELF', ref: '939 JD', priceName: 'lg_grm852hli_price', availName: 'lg_grm852hli_avail' },
          { brand: 'beko', model: 'RDNE710E40SXP', ref: '779 JD', priceName: 'beko_rdne710e40sxp_price', availName: 'beko_rdne710e40sxp_avail' },
          { brand: 'beko', model: 'RDNE710E40SXBR', ref: '799 JD', priceName: 'beko_rdne710e40sxbr_price', availName: 'beko_rdne710e40sxbr_avail' },
          { brand: 'Whirlpool', model: 'WTMF 836653 XME', ref: '850 JD', priceName: 'whirlpool_wtmf836653xme_price', availName: 'whirlpool_wtmf836653xme_avail' },
          { brand: 'Hisense', model: 'RT3N635NAD4 (New)', ref: '749 JD', priceName: 'hisense_rt3n635nad4_price', availName: 'hisense_rt3n635nad4_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_b5rcne565hxpmg',
        brand: 'beko',
        model: 'B5RCNE565HXPMG',
        existsName: 'beko_b5rcne565hxpmg_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'hisense_rb605n4bs1_price', availName: 'hisense_rb605n4bs1_avail' },
          { brand: 'Whirlpool', model: 'W5 711E OX', ref: '450 JD', priceName: 'whirlpool_w5711eox_price', availName: 'whirlpool_w5711eox_avail' },
          { brand: 'Indesit', model: 'LD70 N1 X UK', ref: '499 JD', priceName: 'indesit_ld70n1xuk_price', availName: 'indesit_ld70n1xuk_avail' },
          { brand: 'Indesit', model: 'LI8 SN2E K', ref: '549 JD', priceName: 'indesit_li8sn2ek_price', availName: 'indesit_li8sn2ek_avail' },
          { brand: 'Indesit', model: 'XI9 T2I X', ref: '599 JD', priceName: 'indesit_xi9t2ix_price', availName: 'indesit_xi9t2ix_avail' },
          { brand: 'beko', model: 'B5RCNE565HXPMG', ref: '625 JD', priceName: 'beko_b5rcne565hxpmg_price', availName: 'beko_b5rcne565hxpmg_avail' },
          { brand: 'Hisense', model: 'RB5P504NMI3', ref: '649 JD', priceName: 'hisense_rb5p504nmi3_price', availName: 'hisense_rb5p504nmi3_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'vestel_rm750bf3fdx_price', availName: 'vestel_rm750bf3fdx_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'vestel_rm750bf3fx_price', availName: 'vestel_rm750bf3fx_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_b5rcne66hxb',
        brand: 'beko',
        model: 'B5RCNE66HXB',
        existsName: 'beko_b5rcne66hxb_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'hisense_rb605n4bs1_price', availName: 'hisense_rb605n4bs1_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'vestel_rm750bf3fx_price', availName: 'vestel_rm750bf3fx_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'vestel_rm750bf3fdx_price', availName: 'vestel_rm750bf3fdx_avail' },
          { brand: 'beko', model: 'B5RCNE66HXB', ref: '649 JD', priceName: 'beko_b5rcne66hxb_price', availName: 'beko_b5rcne66hxb_avail' },
        ],
      },
      {
        id: 'card_refrigerators_ariston_arb78f6593xlna',
        brand: 'Ariston',
        model: 'ARB78 F6593 XLNA',
        existsName: 'ariston_arb78f6593xlna_exists',
        competitors: [
          { brand: 'Hisense', model: 'RB605N4BS1', ref: '599 JD', priceName: 'hisense_rb605n4bs1_price', availName: 'hisense_rb605n4bs1_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-X', ref: '629 JD', priceName: 'vestel_rm750bf3fx_price', availName: 'vestel_rm750bf3fx_avail' },
          { brand: 'Vestel', model: 'RM750BF3F-DX', ref: '549 JD', priceName: 'vestel_rm750bf3fdx_price', availName: 'vestel_rm750bf3fdx_avail' },
          { brand: 'beko', model: 'ARB78 F6593 XLNA', ref: '859 JD', priceName: 'ariston_arb78f6593xlna_price', availName: 'ariston_arb78f6593xlna_avail' },
        ],
      },
      {
        id: 'card_refrigerators_ariston_arb78f6593xlna_v2',
        brand: 'Ariston',
        model: 'ARB78 F6593 XLNA',
        existsName: 'ariston_arb78f6593xlna_v2_exists',
        competitors: [
          { brand: 'Ariston', model: 'ARB78 F6593 XLNA', ref: '859 JD', priceName: 'ariston_arb78f6593xlna_v2_price', availName: 'ariston_arb78f6593xlna_v2_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-DXCL', ref: '899 JD', priceName: 'vestel_rm850bf4edxcl_price', availName: 'vestel_rm850bf4edxcl_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-XCL', ref: '719 JD', priceName: 'vestel_rm850bf4excl_price', availName: 'vestel_rm850bf4excl_avail' },
          { brand: 'Whirlpool', model: 'WBMF 836573 XNA', ref: '900 JD', priceName: 'whirlpool_wbmf836573xna_price', availName: 'whirlpool_wbmf836573xna_avail' },
          { brand: 'Bosch', model: 'KGD86AI304', ref: '1099 JD', priceName: 'bosch_kgd86ai304_price', availName: 'bosch_kgd86ai304_avail' },
          { brand: 'Bosch', model: 'KGN86AI32U', ref: '999 JD', priceName: 'bosch_kgn86ai32u_price', availName: 'bosch_kgn86ai32u_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_rcne730e40sxp',
        brand: 'beko',
        model: 'RCNE730E40SXP',
        existsName: 'beko_rcne730e40sxp_exists',
        competitors: [
          { brand: 'Vestel', model: 'RM850BF4E-DXCL', ref: '899 JD', priceName: 'vestel_rm850bf4edxcl_price', availName: 'vestel_rm850bf4edxcl_avail' },
          { brand: 'Vestel', model: 'RM850BF4E-XCL', ref: '719 JD', priceName: 'vestel_rm850bf4excl_price', availName: 'vestel_rm850bf4excl_avail' },
          { brand: 'beko', model: 'RCNE730E40SXP', ref: '799 JD', priceName: 'beko_rcne730e40sxp_price', availName: 'beko_rcne730e40sxp_avail' },
          { brand: 'Whirlpool', model: 'WBMF 836573 XNA', ref: '900 JD', priceName: 'whirlpool_wbmf836573xna_price', availName: 'whirlpool_wbmf836573xna_avail' },
          { brand: 'Bosch', model: 'KGD86AI304', ref: '1099 JD', priceName: 'bosch_kgd86ai304_price', availName: 'bosch_kgd86ai304_avail' },
          { brand: 'Bosch', model: 'KGN86AI32U', ref: '999 JD', priceName: 'bosch_kgn86ai32u_price', availName: 'bosch_kgn86ai32u_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_gn156320xp',
        brand: 'beko',
        model: 'GN156320XP',
        existsName: 'beko_gn156320xp_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS670N4ASU', ref: '549 JD', priceName: 'hisense_rs670n4asu_price', availName: 'hisense_rs670n4asu_avail' },
          { brand: 'Midea', model: 'MDRS710FGF02', ref: '550 JD', priceName: 'midea_mdrs710fgf02_price', availName: 'midea_mdrs710fgf02_avail' },
          { brand: 'beko', model: 'GN156320XP', ref: '599 JD', priceName: 'beko_gn156320xp_price', availName: 'beko_gn156320xp_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'hisense_rs3p725nbg_price', availName: 'hisense_rs3p725nbg_avail' },
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'hisense_rs741n4wsu_price', availName: 'hisense_rs741n4wsu_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_gn164020xp',
        brand: 'beko',
        model: 'GN 164020XP',
        existsName: 'beko_gn164020xp_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'hisense_rs741n4wsu_price', availName: 'hisense_rs741n4wsu_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'hisense_rs3p725nbg_price', availName: 'hisense_rs3p725nbg_avail' },
          { brand: 'beko', model: 'GN 164020XP', ref: '799 JD', priceName: 'beko_gn164020xp_price', availName: 'beko_gn164020xp_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'samsung_rs68a8820s9lv_price', availName: 'samsung_rs68a8820s9lv_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'electrolux_ese6600a_price', availName: 'electrolux_ese6600a_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'samsung_rs66a8100s9lv_price', availName: 'samsung_rs66a8100s9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'lg_gcb287dve_price', availName: 'lg_gcb287dve_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'samsung_rs62r5001m9lv_price', availName: 'samsung_rs62r5001m9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'lg_gcb287dvl_price', availName: 'lg_gcb287dvl_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_gn164022xbr',
        brand: 'beko',
        model: 'GN164022XBR',
        existsName: 'beko_gn164022xbr_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'hisense_rs741n4wsu_price', availName: 'hisense_rs741n4wsu_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'hisense_rs3p725nbg_price', availName: 'hisense_rs3p725nbg_avail' },
          { brand: 'beko', model: 'GN164022XBR', ref: '799 JD', priceName: 'beko_gn164022xbr_price', availName: 'beko_gn164022xbr_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'samsung_rs68a8820s9lv_price', availName: 'samsung_rs68a8820s9lv_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'electrolux_ese6600a_price', availName: 'electrolux_ese6600a_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'samsung_rs66a8100s9lv_price', availName: 'samsung_rs66a8100s9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'lg_gcb287dve_price', availName: 'lg_gcb287dve_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'samsung_rs62r5001m9lv_price', availName: 'samsung_rs62r5001m9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'lg_gcb287dvl_price', availName: 'lg_gcb287dvl_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_gn164020gb',
        brand: 'beko',
        model: 'GN 164020 GB',
        existsName: 'beko_gn164020gb_exists',
        competitors: [
          { brand: 'Hisense', model: 'RS741N4WSU', ref: '699 JD', priceName: 'hisense_rs741n4wsu_price', availName: 'hisense_rs741n4wsu_avail' },
          { brand: 'Hisense', model: 'RS3P725NBG', ref: '599 JD', priceName: 'hisense_rs3p725nbg_price', availName: 'hisense_rs3p725nbg_avail' },
          { brand: 'beko', model: 'GN 164020 GB', ref: '999 JD', priceName: 'beko_gn164020gb_price', availName: 'beko_gn164020gb_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'samsung_rs68a8820s9lv_price', availName: 'samsung_rs68a8820s9lv_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'electrolux_ese6600a_price', availName: 'electrolux_ese6600a_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'samsung_rs66a8100s9lv_price', availName: 'samsung_rs66a8100s9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'lg_gcb287dve_price', availName: 'lg_gcb287dve_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'samsung_rs62r5001m9lv_price', availName: 'samsung_rs62r5001m9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'lg_gcb287dvl_price', availName: 'lg_gcb287dvl_avail' },
        ],
      },
      {
        id: 'card_refrigerators_ariston_ars91f6634xlna',
        brand: 'Ariston',
        model: 'ARS91 F6634 XLNA',
        existsName: 'ariston_ars91f6634xlna_exists',
        competitors: [
          { brand: 'Ariston', model: 'ARS91 F6634 XLNA', ref: '979 JD', priceName: 'ariston_ars91f6634xlna_price', availName: 'ariston_ars91f6634xlna_avail' },
          { brand: 'Samsung', model: 'RS68A8820S9/LV', ref: '999 JD', priceName: 'samsung_rs68a8820s9lv_price', availName: 'samsung_rs68a8820s9lv_avail' },
          { brand: 'Electrolux', model: 'ESE6600A', ref: '849 JD', priceName: 'electrolux_ese6600a_price', availName: 'electrolux_ese6600a_avail' },
          { brand: 'Samsung', model: 'RS66A8100S9/LV', ref: '799 JD', priceName: 'samsung_rs66a8100s9lv_price', availName: 'samsung_rs66a8100s9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVE.ADSPELF', ref: '1149 JD', priceName: 'lg_gcb287dve_price', availName: 'lg_gcb287dve_avail' },
          { brand: 'Samsung', model: 'RS62R5001M9/LV', ref: '799 JD', priceName: 'samsung_rs62r5001m9lv_price', availName: 'samsung_rs62r5001m9lv_avail' },
          { brand: 'LG', model: 'GCB-287DVL.APYPELF', ref: '899 JD', priceName: 'lg_gcb287dvl_price', availName: 'lg_gcb287dvl_avail' },
        ],
      },
      {
        id: 'card_refrigerators_beko_gn1406223px',
        brand: 'beko',
        model: 'GN1406223PX',
        existsName: 'beko_gn1406223px_exists',
        competitors: [
          { brand: 'Samsung', model: 'RF48A4010M9/LV', ref: '999 JD', priceName: 'samsung_rf48a4010m9lv_price', availName: 'samsung_rf48a4010m9lv_avail' },
          { brand: 'Electrolux', model: 'EQE4900A-B', ref: '899 JD', priceName: 'electrolux_eqe4900ab_price', availName: 'electrolux_eqe4900ab_avail' },
          { brand: 'beko', model: 'GN1406223PX', ref: '1049 JD', priceName: 'beko_gn1406223px_price', availName: 'beko_gn1406223px_avail' },
          { brand: 'Hisense', model: 'RQ749N4ASU', ref: '1149 JD', priceName: 'hisense_rq749n4asu_price', availName: 'hisense_rq749n4asu_avail' },
          { brand: 'Hisense', model: 'RS819N4ISU', ref: '999 JD', priceName: 'hisense_rs819n4isu_price', availName: 'hisense_rs819n4isu_avail' },
        ],
      },
    ],
  },
  {
    icon: '🫧',
    title: 'الغسالات',
    sub: 'Washing Machines',
    products: [
      {
        id: 'card_washing_beko_bm1wfu37200bs',
        brand: 'beko',
        model: 'BM1WFU37200BS',
        existsName: 'beko_bm1wfu37200bs_exists',
        competitors: [
          { brand: 'LG', model: 'FH2J3QDNP0.SBWPEL', ref: '299 JD', priceName: 'lg_fh2j3qdnp0_price', availName: 'lg_fh2j3qdnp0_avail' },
          { brand: 'Electrolux', model: 'EW6F5722BB', ref: '199 JD', priceName: 'electrolux_ew6f5722bb_price', availName: 'electrolux_ew6f5722bb_avail' },
          { brand: 'AEG', model: 'LFW6I7261B', ref: '333 JD', priceName: 'aeg_lfw6i7261b_price', availName: 'aeg_lfw6i7261b_avail' },
          { brand: 'Midea', model: 'MF100W70B', ref: '209 JD', priceName: 'midea_mf100w70b_price', availName: 'midea_mf100w70b_avail' },
          { brand: 'Sharp', model: 'ES-FE710DZL-S', ref: '269 JD', priceName: 'sharp_esfe710dzls_price', availName: 'sharp_esfe710dzls_avail' },
          { brand: 'Indesit', model: 'OMTWE 71252 S EU', ref: '300 JD', priceName: 'indesit_omtwe71252seu_price', availName: 'indesit_omtwe71252seu_avail' },
          { brand: 'Conti', model: 'WM 7123 SB', ref: '219 JD', priceName: 'conti_wm7123sb_price', availName: 'conti_wm7123sb_avail' },
          { brand: 'Samsung', model: 'WW70T4020CX1AS', ref: '279 JD', priceName: 'samsung_ww70t4020cx1as_price', availName: 'samsung_ww70t4020cx1as_avail' },
          { brand: 'beko', model: 'BM1WFU37200BS', ref: '229 JD', priceName: 'beko_bm1wfu37200bs_price', availName: 'beko_bm1wfu37200bs_avail' },
          { brand: 'Vestel', model: 'WB712T2DSS', ref: '209 JD', priceName: 'vestel_wb712t2dss_price', availName: 'vestel_wb712t2dss_avail' },
          { brand: 'Conti', model: 'WMP7124TB', ref: '199 JD', priceName: 'conti_wmp7124tb_price', availName: 'conti_wmp7124tb_avail' },
          { brand: 'Hisense', model: 'WFQP7012JT/P', ref: '219 JD', priceName: 'hisense_wfqp7012jtp_price', availName: 'hisense_wfqp7012jtp_avail' },
        ],
      },
      {
        id: 'card_washing_beko_bm3wfu38200bs',
        brand: 'beko',
        model: 'BM3WFU38200BS',
        existsName: 'beko_bm3wfu38200bs_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'lg_f4v5typ0w_price', availName: 'lg_f4v5typ0w_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'lg_f2v3pyp3we_price', availName: 'lg_f2v3pyp3we_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'aeg_lf7384m4b_price', availName: 'aeg_lf7384m4b_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'samsung_ww80ta046ax1fh_price', availName: 'samsung_ww80ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'indesit_bwe81284xwssseu_price', availName: 'indesit_bwe81284xwssseu_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'conti_wms8123s_price', availName: 'conti_wms8123s_avail' },
          { brand: 'Midea', model: 'MF100W80B', ref: '249 JD', priceName: 'midea_mf100w80b_price', availName: 'midea_mf100w80b_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'indesit_xwe81283xseu_price', availName: 'indesit_xwe81283xseu_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'whirlpool_ffb8248sbsvex_price', availName: 'whirlpool_ffb8248sbsvex_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'ariston_ns823cggeg_price', availName: 'ariston_ns823cggeg_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'lg_f2y1typ6j_price', availName: 'lg_f2y1typ6j_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'toshiba_twbh90s2jsk_price', availName: 'toshiba_twbh90s2jsk_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'lg_f4v5typ2p_price', availName: 'lg_f4v5typ2p_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'vestel_w812t2dss_price', availName: 'vestel_w812t2dss_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'whirlpool_wfl08122ssbmj_price', availName: 'whirlpool_wfl08122ssbmj_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'aeg_lf7384u4b_price', availName: 'aeg_lf7384u4b_avail' },
          { brand: 'beko', model: 'BM3WFU38200BS', ref: '279 JD', priceName: 'beko_bm3wfu38200bs_price', availName: 'beko_bm3wfu38200bs_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'conti_wmp8124tb_price', availName: 'conti_wmp8124tb_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'hisense_wfqp8012jts_price', availName: 'hisense_wfqp8012jts_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_ns823cggeg',
        brand: 'Ariston',
        model: 'NS 823C GG EG',
        existsName: 'ariston_ns823cggeg_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'lg_f4v5typ0w_price', availName: 'lg_f4v5typ0w_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'lg_f2v3pyp3we_price', availName: 'lg_f2v3pyp3we_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'aeg_lf7384m4b_price', availName: 'aeg_lf7384m4b_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'samsung_ww80ta046ax1fh_price', availName: 'samsung_ww80ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'indesit_bwe81284xwssseu_price', availName: 'indesit_bwe81284xwssseu_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'conti_wms8123s_price', availName: 'conti_wms8123s_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'indesit_xwe81283xseu_price', availName: 'indesit_xwe81283xseu_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'whirlpool_ffb8248sbsvex_price', availName: 'whirlpool_ffb8248sbsvex_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'ariston_ns823cggeg_price', availName: 'ariston_ns823cggeg_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'lg_f2y1typ6j_price', availName: 'lg_f2y1typ6j_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'toshiba_twbh90s2jsk_price', availName: 'toshiba_twbh90s2jsk_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'lg_f4v5typ2p_price', availName: 'lg_f4v5typ2p_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'vestel_w812t2dss_price', availName: 'vestel_w812t2dss_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'whirlpool_wfl08122ssbmj_price', availName: 'whirlpool_wfl08122ssbmj_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'aeg_lf7384u4b_price', availName: 'aeg_lf7384u4b_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'conti_wmp8124tb_price', availName: 'conti_wmp8124tb_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'hisense_wfqp8012jts_price', availName: 'hisense_wfqp8012jts_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_nm11823sseg',
        brand: 'Ariston',
        model: 'NM11 823 SS EG',
        existsName: 'ariston_nm11823sseg_exists',
        competitors: [
          { brand: 'LG', model: 'F4V5TYP0W', ref: '419 JD', priceName: 'lg_f4v5typ0w_price', availName: 'lg_f4v5typ0w_avail' },
          { brand: 'LG', model: 'F2V3PYP3WE', ref: '389 JD', priceName: 'lg_f2v3pyp3we_price', availName: 'lg_f2v3pyp3we_avail' },
          { brand: 'AEG', model: 'LF7384M4B', ref: '499 JD', priceName: 'aeg_lf7384m4b_price', availName: 'aeg_lf7384m4b_avail' },
          { brand: 'Samsung', model: 'WW80TA046AX1FH', ref: '329 JD', priceName: 'samsung_ww80ta046ax1fh_price', availName: 'samsung_ww80ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'BWE 81284X WSSS EU', ref: '389 JD', priceName: 'indesit_bwe81284xwssseu_price', availName: 'indesit_bwe81284xwssseu_avail' },
          { brand: 'Conti', model: 'WM-S8123-S', ref: '259 JD', priceName: 'conti_wms8123s_price', availName: 'conti_wms8123s_avail' },
          { brand: 'Indesit', model: 'XWE 81283X S EU', ref: '389 JD', priceName: 'indesit_xwe81283xseu_price', availName: 'indesit_xwe81283xseu_avail' },
          { brand: 'Whirlpool', model: 'FFB 8248 SBSV EX', ref: '499 JD', priceName: 'whirlpool_ffb8248sbsvex_price', availName: 'whirlpool_ffb8248sbsvex_avail' },
          { brand: 'Ariston', model: 'NS 823C GG EG', ref: '299 JD', priceName: 'ariston_ns823cggeg_price', availName: 'ariston_ns823cggeg_avail' },
          { brand: 'LG', model: 'F2Y1TYP6J', ref: '389 JD', priceName: 'lg_f2y1typ6j_price', availName: 'lg_f2y1typ6j_avail' },
          { brand: 'Toshiba', model: 'TW-BH90S2J(SK)', ref: '269 JD', priceName: 'toshiba_twbh90s2jsk_price', availName: 'toshiba_twbh90s2jsk_avail' },
          { brand: 'LG', model: 'F4V5TYP2P.SPTPEL', ref: '439 JD', priceName: 'lg_f4v5typ2p_price', availName: 'lg_f4v5typ2p_avail' },
          { brand: 'Vestel', model: 'W812T2DSS (Without Inverter)', ref: '239 JD', priceName: 'vestel_w812t2dss_price', availName: 'vestel_w812t2dss_avail' },
          { brand: 'Ariston', model: 'NM11 823 SS EG', ref: '339 JD', priceName: 'ariston_nm11823sseg_price', availName: 'ariston_nm11823sseg_avail' },
          { brand: 'Whirlpool', model: 'WFL 08122S SBMJ', ref: '330 JD', priceName: 'whirlpool_wfl08122ssbmj_price', availName: 'whirlpool_wfl08122ssbmj_avail' },
          { brand: 'AEG', model: 'LF7384U4B', ref: '549 JD', priceName: 'aeg_lf7384u4b_price', availName: 'aeg_lf7384u4b_avail' },
          { brand: 'conti', model: 'WMP8124TB', ref: '229 JD', priceName: 'conti_wmp8124tb_price', availName: 'conti_wmp8124tb_avail' },
          { brand: 'Hisense', model: 'WFQP8012JT/S', ref: '249 JD', priceName: 'hisense_wfqp8012jts_price', availName: 'hisense_wfqp8012jts_avail' },
        ],
      },
      {
        id: 'card_washing_beko_b5wft091400mg',
        brand: 'beko',
        model: 'B5WFT091400MG',
        existsName: 'beko_b5wft091400mg_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'samsung_ww90cgc0edaefh_new_price', availName: 'samsung_ww90cgc0edaefh_new_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'lg_f4v5vyp0w_price', availName: 'lg_f4v5vyp0w_avail' },
          { brand: 'Media', model: 'MF200W90WB/T', ref: '279 JD', priceName: 'midea_mf200w90wbt_price', availName: 'midea_mf200w90wbt_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'samsung_ww90ta046ax1fh_price', availName: 'samsung_ww90ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'indesit_xwe91483xseu_price', availName: 'indesit_xwe91483xseu_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'ariston_nlm11946scaex_price', availName: 'ariston_nlm11946scaex_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_price', availName: 'samsung_ww90cgc0edabfh_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'lg_f4v5vyp2t_price', availName: 'lg_f4v5vyp2t_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'whirlpool_ffd9448sbcvex_price', availName: 'whirlpool_ffd9448sbcvex_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'aeg_lf8394u4o_price', availName: 'aeg_lf8394u4o_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'vestel_wb9b14t2tdss_price', availName: 'vestel_wb9b14t2tdss_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'vestel_wb9b14t2tdxs_price', availName: 'vestel_wb9b14t2tdxs_avail' },
          { brand: 'beko', model: 'B5WFT091400MG', ref: '329 JD', priceName: 'beko_b5wft091400mg_price', availName: 'beko_b5wft091400mg_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_new_price', availName: 'samsung_ww90cgc0edabfh_new_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_nlm11946scaex',
        brand: 'Ariston',
        model: 'NLM11 946 SC A EX',
        existsName: 'ariston_nlm11946scaex_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'samsung_ww90cgc0edaefh_new_price', availName: 'samsung_ww90cgc0edaefh_new_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'lg_f4v5vyp0w_price', availName: 'lg_f4v5vyp0w_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'samsung_ww90ta046ax1fh_price', availName: 'samsung_ww90ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'indesit_xwe91483xseu_price', availName: 'indesit_xwe91483xseu_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'ariston_nlm11946scaex_price', availName: 'ariston_nlm11946scaex_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_price', availName: 'samsung_ww90cgc0edabfh_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'lg_f4v5vyp2t_price', availName: 'lg_f4v5vyp2t_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'whirlpool_ffd9448sbcvex_price', availName: 'whirlpool_ffd9448sbcvex_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'aeg_lf8394u4o_price', availName: 'aeg_lf8394u4o_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'vestel_wb9b14t2tdss_price', availName: 'vestel_wb9b14t2tdss_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'vestel_wb9b14t2tdxs_price', availName: 'vestel_wb9b14t2tdxs_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_new_price', availName: 'samsung_ww90cgc0edabfh_new_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_arwf09122smmj',
        brand: 'Ariston',
        model: 'ARWF 09122S MMJ',
        existsName: 'ariston_arwf09122smmj_exists',
        competitors: [
          { brand: 'Samsung', model: 'WW90CGC0EDAEFH (New)', ref: '369 JD', priceName: 'samsung_ww90cgc0edaefh_new_price', availName: 'samsung_ww90cgc0edaefh_new_avail' },
          { brand: 'LG', model: 'F4V5VYP0W.SBWPEL', ref: '499 JD', priceName: 'lg_f4v5vyp0w_price', availName: 'lg_f4v5vyp0w_avail' },
          { brand: 'Samsung', model: 'WW90TA046AX1FH', ref: '349 JD', priceName: 'samsung_ww90ta046ax1fh_price', availName: 'samsung_ww90ta046ax1fh_avail' },
          { brand: 'Indesit', model: 'XWE 91483X S EU', ref: '449 JD', priceName: 'indesit_xwe91483xseu_price', availName: 'indesit_xwe91483xseu_avail' },
          { brand: 'Ariston', model: 'NLM11 946 SC A EX', ref: '399 JD', priceName: 'ariston_nlm11946scaex_price', availName: 'ariston_nlm11946scaex_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_price', availName: 'samsung_ww90cgc0edabfh_avail' },
          { brand: 'Ariston', model: 'ARWF 09122S MMJ', ref: '399 JD', priceName: 'ariston_arwf09122smmj_price', availName: 'ariston_arwf09122smmj_avail' },
          { brand: 'LG', model: 'F4V5VYP2T.SSSPEL', ref: '519 JD', priceName: 'lg_f4v5vyp2t_price', availName: 'lg_f4v5vyp2t_avail' },
          { brand: 'Whirlpool', model: 'FFD 9448 SBCV EX', ref: '550 JD', priceName: 'whirlpool_ffd9448sbcvex_price', availName: 'whirlpool_ffd9448sbcvex_avail' },
          { brand: 'AEG', model: 'LF8394U4O', ref: '649 JD', priceName: 'aeg_lf8394u4o_price', availName: 'aeg_lf8394u4o_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDSS', ref: '309 JD', priceName: 'vestel_wb9b14t2tdss_price', availName: 'vestel_wb9b14t2tdss_avail' },
          { brand: 'Vestel', model: 'WB9B14T2TDXS', ref: '289 JD', priceName: 'vestel_wb9b14t2tdxs_price', availName: 'vestel_wb9b14t2tdxs_avail' },
          { brand: 'Samsung', model: 'WW90CGC0EDABFH (New)', ref: '349 JD', priceName: 'samsung_ww90cgc0edabfh_new_price', availName: 'samsung_ww90cgc0edabfh_new_avail' },
        ],
      },
      {
        id: 'card_washing_beko_b3wfu51042mg',
        brand: 'beko',
        model: 'B3WFU51042MG',
        existsName: 'beko_b3wfu51042mg_exists',
        competitors: [
          { brand: 'Indesit', model: 'BWE 101484X WSSS EU', ref: '599 JD', priceName: 'indesit_bwe101484xwssseu_price', availName: 'indesit_bwe101484xwssseu_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'samsung_ww11b1a046abfh_price', availName: 'samsung_ww11b1a046abfh_avail' },
          { brand: 'Whirlpool', model: 'FFD 10449 SBCV GCC', ref: '699 JD', priceName: 'whirlpool_ffd10449sbcvgcc_price', availName: 'whirlpool_ffd10449sbcvgcc_avail' },
          { brand: 'Vestel', model: 'WB1014T3DSS', ref: '349 JD', priceName: 'vestel_wb1014t3dss_price', availName: 'vestel_wb1014t3dss_avail' },
          { brand: 'Vestel', model: 'WB1014T3DXS', ref: '329 JD', priceName: 'vestel_wb1014t3dxs_price', availName: 'vestel_wb1014t3dxs_avail' },
          { brand: 'beko', model: 'B3WFU51042MG', ref: '429 JD', priceName: 'beko_b3wfu51042mg_price', availName: 'beko_b3wfu51042mg_avail' },
          { brand: 'Hisense', model: 'WF3S1043BT (Wifi)', ref: '369 JD', priceName: 'hisense_wf3s1043bt_price', availName: 'hisense_wf3s1043bt_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_arwf10143dmmj',
        brand: 'Ariston',
        model: 'ARWF 10143D MMJ',
        existsName: 'ariston_arwf10143dmmj_exists',
        competitors: [
          { brand: 'Indesit', model: 'BWE 101484X WSSS EU', ref: '599 JD', priceName: 'indesit_bwe101484xwssseu_price', availName: 'indesit_bwe101484xwssseu_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'samsung_ww11b1a046abfh_price', availName: 'samsung_ww11b1a046abfh_avail' },
          { brand: 'Whirlpool', model: 'FFD 10449 SBCV GCC', ref: '699 JD', priceName: 'whirlpool_ffd10449sbcvgcc_price', availName: 'whirlpool_ffd10449sbcvgcc_avail' },
          { brand: 'Vestel', model: 'WB1014T3DSS', ref: '349 JD', priceName: 'vestel_wb1014t3dss_price', availName: 'vestel_wb1014t3dss_avail' },
          { brand: 'Vestel', model: 'WB1014T3DXS', ref: '329 JD', priceName: 'vestel_wb1014t3dxs_price', availName: 'vestel_wb1014t3dxs_avail' },
          { brand: 'Ariston', model: 'ARWF 10143D MMJ', ref: '429 JD', priceName: 'ariston_arwf10143dmmj_price', availName: 'ariston_arwf10143dmmj_avail' },
          { brand: 'Hisense', model: 'WF3S1043BT (Wifi)', ref: '369 JD', priceName: 'hisense_wf3s1043bt_price', availName: 'hisense_wf3s1043bt_avail' },
        ],
      },
      {
        id: 'card_washing_ariston_nllcd1165scadex',
        brand: 'Ariston',
        model: 'NLLCD 1165 SC AD EX',
        existsName: 'ariston_nllcd1165scadex_exists',
        competitors: [
          { brand: 'Ariston', model: 'NLLCD 1165 SC AD EX', ref: '599 JD', priceName: 'ariston_nllcd1165scadex_price', availName: 'ariston_nllcd1165scadex_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'samsung_ww11b1a046abfh_price', availName: 'samsung_ww11b1a046abfh_avail' },
          { brand: 'AEG', model: 'LF8504G6Q', ref: '749 JD', priceName: 'aeg_lf8504g6q_price', availName: 'aeg_lf8504g6q_avail' },
          { brand: 'Hisense', model: 'WF5S1245BB', ref: '499 JD', priceName: 'hisense_wf5s1245bb_price', availName: 'hisense_wf5s1245bb_avail' },
          { brand: 'Hisense', model: 'WFQA1214EVJMT-JO', ref: '419 JD', priceName: 'hisense_wfqa1214evjmtjo_price', availName: 'hisense_wfqa1214evjmtjo_avail' },
          { brand: 'Vestel', model: 'WB1214T3DXS-JO', ref: '379 JD', priceName: 'vestel_wb1214t3dxsjo_price', availName: 'vestel_wb1214t3dxsjo_avail' },
          { brand: 'Hisense', model: 'WF3S1243BT', ref: '449 JD', priceName: 'hisense_wf3s1243bt_price', availName: 'hisense_wf3s1243bt_avail' },
        ],
      },
      {
        id: 'card_washing_beko_bm3wft412400bs',
        brand: 'beko',
        model: 'BM3WFT412400BS',
        existsName: 'beko_bm3wft412400bs_exists',
        competitors: [
          { brand: 'Ariston', model: 'NLLCD 1165 SC AD EX', ref: '599 JD', priceName: 'ariston_nllcd1165scadex_price', availName: 'ariston_nllcd1165scadex_avail' },
          { brand: 'Samsung', model: 'WW11B1A046ABFH', ref: '439 JD', priceName: 'samsung_ww11b1a046abfh_price', availName: 'samsung_ww11b1a046abfh_avail' },
          { brand: 'AEG', model: 'LF8504G6Q', ref: '749 JD', priceName: 'aeg_lf8504g6q_price', availName: 'aeg_lf8504g6q_avail' },
          { brand: 'Hisense', model: 'WF5S1245BB', ref: '499 JD', priceName: 'hisense_wf5s1245bb_price', availName: 'hisense_wf5s1245bb_avail' },
          { brand: 'Hisense', model: 'WFQA1214EVJMT-JO', ref: '419 JD', priceName: 'hisense_wfqa1214evjmtjo_price', availName: 'hisense_wfqa1214evjmtjo_avail' },
          { brand: 'Vestel', model: 'WB1214T3DXS-JO', ref: '379 JD', priceName: 'vestel_wb1214t3dxsjo_price', availName: 'vestel_wb1214t3dxsjo_avail' },
          { brand: 'beko', model: 'BM3WFT412400BS', ref: '499 JD', priceName: 'beko_bm3wft412400bs_price', availName: 'beko_bm3wft412400bs_avail' },
          { brand: 'Hisense', model: 'WF3S1243BT', ref: '449 JD', priceName: 'hisense_wf3s1243bt_price', availName: 'hisense_wf3s1243bt_avail' },
        ],
      },
    ],
  },
  {
    icon: '♨️',
    title: 'المجففات',
    sub: 'Dryers',
    products: [
      {
        id: 'card_dryers_beko_b5t68254mg',
        brand: 'beko',
        model: 'B5T68254MG',
        existsName: 'beko_b5t68254mg_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M10 8X1S EX', ref: '—', priceName: 'ariston_ntm108x1sex_price', availName: 'ariston_ntm108x1sex_avail' },
          { brand: 'Whirlpool', model: 'FFT M11 8X 1SBS', ref: '575 JD', priceName: 'whirlpool_fftm118x1sbs_price', availName: 'whirlpool_fftm118x1sbs_avail' },
          { brand: 'Whirlpool', model: 'FFT M11 81S EX', ref: '575 JD', priceName: 'whirlpool_fftm1181sex_price', availName: 'whirlpool_fftm1181sex_avail' },
          { brand: 'Samsung', model: 'DV80TA020AX/EU', ref: '509 JD', priceName: 'samsung_dv80ta020axeu_price', availName: 'samsung_dv80ta020axeu_avail' },
          { brand: 'Vestel', model: 'TDH8SGT3DX', ref: '389 JD', priceName: 'vestel_tdh8sgt3dx_price', availName: 'vestel_tdh8sgt3dx_avail' },
        ],
      },
      {
        id: 'card_dryers_beko_b5t69254mg',
        brand: 'beko',
        model: 'B5T69254MG',
        existsName: 'beko_b5t69254mg_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M11 9X1SXB EX', ref: '559 JD', priceName: 'ariston_ntm119x1sxbex_price', availName: 'ariston_ntm119x1sxbex_avail' },
          { brand: 'Conti', model: 'TD-HP92-S', ref: '349 JD', priceName: 'conti_tdhp92s_price', availName: 'conti_tdhp92s_avail' },
          { brand: 'Whirlpool', model: 'FFT D 9X 3SK EX', ref: '699 JD', priceName: 'whirlpool_fftd9x3skex_price', availName: 'whirlpool_fftd9x3skex_avail' },
          { brand: 'Samsung', model: 'DV90T6240LX/FH', ref: '549 JD', priceName: 'samsung_dv90t6240lxfh_price', availName: 'samsung_dv90t6240lxfh_avail' },
          { brand: 'AEG', model: 'EW8H1966TBS', ref: '799 JD', priceName: 'aeg_ew8h1966tbs_price', availName: 'aeg_ew8h1966tbs_avail' },
          { brand: 'Samsung', model: 'DV90BB7440GBFH (Bespoke)', ref: '719 JD', priceName: 'samsung_dv90bb7440gbfh_price', availName: 'samsung_dv90bb7440gbfh_avail' },
          { brand: 'Samsung', model: 'DV90T7240BX/FH', ref: '549 JD', priceName: 'samsung_dv90t7240bxfh_price', availName: 'samsung_dv90t7240bxfh_avail' },
          { brand: 'Vestel', model: 'TDH9SGT3DX', ref: '449 JD', priceName: 'vestel_tdh9sgt3dx_price', availName: 'vestel_tdh9sgt3dx_avail' },
          { brand: 'Hisense', model: 'DH3S902BT', ref: '399 JD', priceName: 'hisense_dh3s902bt_price', availName: 'hisense_dh3s902bt_avail' },
          { brand: 'Samsung', model: 'DV90DG52A0ABEU', ref: '499 JD', priceName: 'samsung_dv90dg52a0abeu_price', availName: 'samsung_dv90dg52a0abeu_avail' },
        ],
      },
      {
        id: 'card_dryers_ariston_ardh092s25mmj',
        brand: 'Ariston',
        model: 'ARDH 092S 25 MMJ',
        existsName: 'ariston_ardh092s25mmj_exists',
        competitors: [
          { brand: 'Ariston', model: 'NT M11 9X1SXB EX', ref: '559 JD', priceName: 'ariston_ntm119x1sxbex_price', availName: 'ariston_ntm119x1sxbex_avail' },
          { brand: 'Conti', model: 'TD-HP92-S', ref: '349 JD', priceName: 'conti_tdhp92s_price', availName: 'conti_tdhp92s_avail' },
          { brand: 'Whirlpool', model: 'FFT D 9X 3SK EX', ref: '699 JD', priceName: 'whirlpool_fftd9x3skex_price', availName: 'whirlpool_fftd9x3skex_avail' },
          { brand: 'Samsung', model: 'DV90T6240LX/FH', ref: '549 JD', priceName: 'samsung_dv90t6240lxfh_price', availName: 'samsung_dv90t6240lxfh_avail' },
          { brand: 'AEG', model: 'EW8H1966TBS', ref: '799 JD', priceName: 'aeg_ew8h1966tbs_price', availName: 'aeg_ew8h1966tbs_avail' },
          { brand: 'Samsung', model: 'DV90BB7440GBFH (Bespoke)', ref: '719 JD', priceName: 'samsung_dv90bb7440gbfh_price', availName: 'samsung_dv90bb7440gbfh_avail' },
          { brand: 'Samsung', model: 'DV90T7240BX/FH', ref: '549 JD', priceName: 'samsung_dv90t7240bxfh_price', availName: 'samsung_dv90t7240bxfh_avail' },
          { brand: 'Vestel', model: 'TDH9SGT3DX', ref: '449 JD', priceName: 'vestel_tdh9sgt3dx_price', availName: 'vestel_tdh9sgt3dx_avail' },
          { brand: 'Hisense', model: 'DH3S902BT', ref: '399 JD', priceName: 'hisense_dh3s902bt_price', availName: 'hisense_dh3s902bt_avail' },
          { brand: 'Samsung', model: 'DV90DG52A0ABEU', ref: '499 JD', priceName: 'samsung_dv90dg52a0abeu_price', availName: 'samsung_dv90dg52a0abeu_avail' },
        ],
      },
      {
        id: 'card_dryers_ariston_ardh103dmmj',
        brand: 'Ariston',
        model: 'ARDH 103D MMJ',
        existsName: 'ariston_ardh103dmmj_exists',
        competitors: [
          { brand: 'Hisense', model: 'DH5S102BB', ref: '499 JD', priceName: 'hisense_dh5s102bb_price', availName: 'hisense_dh5s102bb_avail' },
        ],
      },
      {
        id: 'card_dryers_beko_bm3t12nxs',
        brand: 'beko',
        model: 'BM3T12NXS',
        existsName: 'beko_bm3t12nxs_exists',
        competitors: [
          { brand: 'Hisense', model: 'DH5S102BB', ref: '499 JD', priceName: 'hisense_dh5s102bb_price', availName: 'hisense_dh5s102bb_avail' },
        ],
      },
    ],
  },
  {
    icon: '🔄',
    title: 'غسالة + مجفف',
    sub: 'Washer & Dryer',
    products: [
      {
        id: 'card_washerdryer_beko_b3dft51042mg',
        brand: 'beko',
        model: 'B3DFT51042MG',
        existsName: 'beko_b3dft51042mg_exists',
        competitors: [
          { brand: 'Samsung', model: 'WD80T554DBN/FH', ref: '559 JD', priceName: 'samsung_wd80t554dbnfh_price', availName: 'samsung_wd80t554dbnfh_avail' },
          { brand: 'LG', model: 'F4V9VCP2E.SBLPEL', ref: '619 JD', priceName: 'lg_f4v9vcp2e_price', availName: 'lg_f4v9vcp2e_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DX', ref: '549 JD', priceName: 'vestel_wdb9b14t3dx_price', availName: 'vestel_wdb9b14t3dx_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DS', ref: '549 JD', priceName: 'vestel_wdb9b14t3ds_price', availName: 'vestel_wdb9b14t3ds_avail' },
          { brand: 'Indesit', model: 'XWDE 961480X S EU', ref: '649 JD', priceName: 'indesit_xwde961480xseu_price', availName: 'indesit_xwde961480xseu_avail' },
          { brand: 'Indesit', model: 'BDE 964 SSV GCC', ref: '700 JD', priceName: 'indesit_bde964ssvgcc_price', availName: 'indesit_bde964ssvgcc_avail' },
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'lg_f4v9rcp2e_price', availName: 'lg_f4v9rcp2e_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'samsung_wd10t654dbns1_price', availName: 'samsung_wd10t654dbns1_avail' },
        ],
      },
      {
        id: 'card_washerdryer_ariston_ndb96ssex',
        brand: 'Ariston',
        model: 'NDB 96 SS EX',
        existsName: 'ariston_ndb96ssex_exists',
        competitors: [
          { brand: 'Samsung', model: 'WD80T554DBN/FH', ref: '559 JD', priceName: 'samsung_wd80t554dbnfh_price', availName: 'samsung_wd80t554dbnfh_avail' },
          { brand: 'LG', model: 'F4V9VCP2E.SBLPEL', ref: '619 JD', priceName: 'lg_f4v9vcp2e_price', availName: 'lg_f4v9vcp2e_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DX', ref: '549 JD', priceName: 'vestel_wdb9b14t3dx_price', availName: 'vestel_wdb9b14t3dx_avail' },
          { brand: 'Vestel', model: 'WDB9B14T3DS', ref: '549 JD', priceName: 'vestel_wdb9b14t3ds_price', availName: 'vestel_wdb9b14t3ds_avail' },
          { brand: 'Indesit', model: 'XWDE 961480X S EU', ref: '649 JD', priceName: 'indesit_xwde961480xseu_price', availName: 'indesit_xwde961480xseu_avail' },
          { brand: 'Indesit', model: 'BDE 964 SSV GCC', ref: '700 JD', priceName: 'indesit_bde964ssvgcc_price', availName: 'indesit_bde964ssvgcc_avail' },
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'lg_f4v9rcp2e_price', availName: 'lg_f4v9rcp2e_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'samsung_wd10t654dbns1_price', availName: 'samsung_wd10t654dbns1_avail' },
        ],
      },
      {
        id: 'card_washerdryer_ariston_ndd1170ssaex',
        brand: 'Ariston',
        model: 'NDD 1170 SSA EX',
        existsName: 'ariston_ndd1170ssaex_exists',
        competitors: [
          { brand: 'LG', model: 'F4V9RCP2E.SBLPEL', ref: '739 JD', priceName: 'lg_f4v9rcp2e_price', availName: 'lg_f4v9rcp2e_avail' },
          { brand: 'Samsung', model: 'WD10T654DBN/S1', ref: '669 JD', priceName: 'samsung_wd10t654dbns1_price', availName: 'samsung_wd10t654dbns1_avail' },
          { brand: 'Midea', model: 'MF200D120WB', ref: '499 JD', priceName: 'midea_mf200d120wb_price', availName: 'midea_mf200d120wb_avail' },
        ],
      },
    ],
  },
  {
    icon: '🍽️',
    title: 'غسالة الجلي',
    sub: 'Dishwashers',
    products: [
      {
        id: 'card_dishwashers_beko_dvn05321sjo',
        brand: 'beko',
        model: 'DVN 05321S-JO',
        existsName: 'beko_dvn05321sjo_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5050FS', ref: '—', priceName: 'samsung_dw60m5050fs_price', availName: 'samsung_dw60m5050fs_avail' },
          { brand: 'Whirlpool', model: 'WFE 2B19 N X', ref: '—', priceName: 'whirlpool_wfe2b19nx_price', availName: 'whirlpool_wfe2b19nx_avail' },
          { brand: 'Ariston', model: 'LFC 2B19 X', ref: '—', priceName: 'ariston_lfc2b19x_price', availName: 'ariston_lfc2b19x_avail' },
          { brand: 'Hisense', model: 'H13DESS', ref: '—', priceName: 'hisense_h13dess_price', availName: 'hisense_h13dess_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bdfn16422s',
        brand: 'beko',
        model: 'BDFN16422S',
        existsName: 'beko_bdfn16422s_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-MB612-SS2', ref: '—', priceName: 'sharp_qwmb612ss2_price', availName: 'sharp_qwmb612ss2_avail' },
          { brand: 'Conti', model: 'DW-71B23-SL', ref: '183 JD', priceName: 'conti_dw71b23sl_price', availName: 'conti_dw71b23sl_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bdfn16422b',
        brand: 'beko',
        model: 'BDFN16422B',
        existsName: 'beko_bdfn16422b_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-V615-BK3', ref: '—', priceName: 'sharp_qwv615bk3_price', availName: 'sharp_qwv615bk3_avail' },
          { brand: 'Conti', model: 'DW-6L-23-BK', ref: '—', priceName: 'conti_dw6l23bk_price', availName: 'conti_dw6l23bk_avail' },
          { brand: 'Vestel', model: 'DWFA1E6B0X', ref: '202 JD', priceName: 'vestel_dwfa1e6b0x_price', availName: 'vestel_dwfa1e6b0x_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bdfn36422xq',
        brand: 'beko',
        model: 'BDFN36422XQ',
        existsName: 'beko_bdfn36422xq_exists',
        competitors: [
          { brand: 'Sharp', model: 'QW-MB612-SS2', ref: '—', priceName: 'sharp_qwmb612ss2_price', availName: 'sharp_qwmb612ss2_avail' },
          { brand: 'Indesit', model: 'DFC 2B+16 AC X', ref: '—', priceName: 'indesit_dfc2b16acx_price', availName: 'indesit_dfc2b16acx_avail' },
          { brand: 'Conti', model: 'DW-71B23-SL', ref: '183 JD', priceName: 'conti_dw71b23sl_price', availName: 'conti_dw71b23sl_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lfc3c26wx',
        brand: 'Ariston',
        model: 'LFC 3C26 W X',
        existsName: 'ariston_lfc3c26wx_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'samsung_dw60m5070fsfh_price', availName: 'samsung_dw60m5070fsfh_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'sharp_qwma814ss2_price', availName: 'sharp_qwma814ss2_avail' },
          { brand: 'Vestel', model: 'DWFA328B1X', ref: '255 JD', priceName: 'vestel_dwfa328b1x_price', availName: 'vestel_dwfa328b1x_avail' },
          { brand: 'Hisense', model: 'HS622E91X', ref: '228 JD', priceName: 'hisense_hs622e91x_price', availName: 'hisense_hs622e91x_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'hisense_hs623e90x_price', availName: 'hisense_hs623e90x_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'conti_dw81l23ix_price', availName: 'conti_dw81l23ix_avail' },
          { brand: 'AEG', model: 'FFB73727PM', ref: '—', priceName: 'aeg_ffb73727pm_price', availName: 'aeg_ffb73727pm_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'vestel_dwfa238b4x_price', availName: 'vestel_dwfa238b4x_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'whirlpool_wfc3c33pfx_price', availName: 'whirlpool_wfc3c33pfx_avail' },
          { brand: 'Electrolux', model: 'ESS47311SX', ref: '—', priceName: 'electrolux_ess47311sx_price', availName: 'electrolux_ess47311sx_avail' },
          { brand: 'Vestel', model: 'DWFA358B1X', ref: '—', priceName: 'vestel_dwfa358b1x_price', availName: 'vestel_dwfa358b1x_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'indesit_dfo3t133afx_price', availName: 'indesit_dfo3t133afx_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bden38523xq',
        brand: 'beko',
        model: 'BDEN38523XQ',
        existsName: 'beko_bden38523xq_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'samsung_dw60m5070fsfh_price', availName: 'samsung_dw60m5070fsfh_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'sharp_qwma814ss2_price', availName: 'sharp_qwma814ss2_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'whirlpool_wfc3c33pfx_price', availName: 'whirlpool_wfc3c33pfx_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'vestel_dwfa238b4x_price', availName: 'vestel_dwfa238b4x_avail' },
          { brand: 'Vestel', model: 'DWFA328B1X', ref: '255 JD', priceName: 'vestel_dwfa328b1x_price', availName: 'vestel_dwfa328b1x_avail' },
          { brand: 'Hisense', model: 'HS622E91X', ref: '228 JD', priceName: 'hisense_hs622e91x_price', availName: 'hisense_hs622e91x_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'hisense_hs623e90x_price', availName: 'hisense_hs623e90x_avail' },
          { brand: 'Electrolux', model: 'ESS47311SX', ref: '—', priceName: 'electrolux_ess47311sx_price', availName: 'electrolux_ess47311sx_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'conti_dw81l23ix_price', availName: 'conti_dw81l23ix_avail' },
          { brand: 'AEG', model: 'FFB73727PM', ref: '—', priceName: 'aeg_ffb73727pm_price', availName: 'aeg_ffb73727pm_avail' },
          { brand: 'Vestel', model: 'DWFA358B1X', ref: '—', priceName: 'vestel_dwfa358b1x_price', availName: 'vestel_dwfa358b1x_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'indesit_dfo3t133afx_price', availName: 'indesit_dfo3t133afx_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bden38523mg',
        brand: 'beko',
        model: 'BDEN38523MG',
        existsName: 'beko_bden38523mg_exists',
        competitors: [
          { brand: 'Samsung', model: 'DW60M5070FS/FH', ref: '240 JD', priceName: 'samsung_dw60m5070fsfh_price', availName: 'samsung_dw60m5070fsfh_avail' },
          { brand: 'Sharp', model: 'QW-MA814-SS2', ref: '—', priceName: 'sharp_qwma814ss2_price', availName: 'sharp_qwma814ss2_avail' },
          { brand: 'Conti', model: 'DW-81L33-DIX', ref: '—', priceName: 'conti_dw81l33dix_price', availName: 'conti_dw81l33dix_avail' },
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'whirlpool_wfc3c33pfx_price', availName: 'whirlpool_wfc3c33pfx_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'vestel_dwfa238b4x_price', availName: 'vestel_dwfa238b4x_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'hisense_hs623e90x_price', availName: 'hisense_hs623e90x_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'conti_dw81l23ix_price', availName: 'conti_dw81l23ix_avail' },
          { brand: 'AEG', model: 'FFB83836PM', ref: '—', priceName: 'aeg_ffb83836pm_price', availName: 'aeg_ffb83836pm_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'indesit_dfo3t133afx_price', availName: 'indesit_dfo3t133afx_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lfc3c33wfx',
        brand: 'Ariston',
        model: 'LFC 3C33 WF X',
        existsName: 'ariston_lfc3c33wfx_exists',
        competitors: [
          { brand: 'Whirlpool', model: 'WFC 3C33 PF X', ref: '—', priceName: 'whirlpool_wfc3c33pfx_price', availName: 'whirlpool_wfc3c33pfx_avail' },
          { brand: 'Vestel', model: 'DWFA238B4X', ref: '252 JD', priceName: 'vestel_dwfa238b4x_price', availName: 'vestel_dwfa238b4x_avail' },
          { brand: 'Hisense', model: 'HS623E90X', ref: '248 JD', priceName: 'hisense_hs623e90x_price', availName: 'hisense_hs623e90x_avail' },
          { brand: 'Conti', model: 'DW-81L23-IX', ref: '—', priceName: 'conti_dw81l23ix_price', availName: 'conti_dw81l23ix_avail' },
          { brand: 'AEG', model: 'FFB83836PM', ref: '—', priceName: 'aeg_ffb83836pm_price', availName: 'aeg_ffb83836pm_avail' },
          { brand: 'Indesit', model: 'DFO 3T133 AF X', ref: '—', priceName: 'indesit_dfo3t133afx_price', availName: 'indesit_dfo3t133afx_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lfo3p31wl',
        brand: 'Ariston',
        model: 'LFO 3P31 WL',
        existsName: 'ariston_lfo3p31wl_exists',
        competitors: [
          { brand: 'LG', model: 'DFB512FW.ABWPELF Direct Drive', ref: '370 JD', priceName: 'lg_dfb512fw_price', availName: 'lg_dfb512fw_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'lg_dfb512fp_price', availName: 'lg_dfb512fp_avail' },
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'vestel_dwa4510b3x_price', availName: 'vestel_dwa4510b3x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'vestel_dwfa4310b1x_price', availName: 'vestel_dwfa4310b1x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'vestel_dwfa4310b1dx_price', availName: 'vestel_dwfa4310b1dx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'whirlpool_wfo3t133pfx_price', availName: 'whirlpool_wfo3t133pfx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'whirlpool_wfo3o41plxuk_price', availName: 'whirlpool_wfo3o41plxuk_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'lg_dfb425fp_price', availName: 'lg_dfb425fp_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'samsung_dw60dg790fslfh_price', availName: 'samsung_dw60dg790fslfh_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lfo3p31wlx',
        brand: 'Ariston',
        model: 'LFO 3P31 WL X',
        existsName: 'ariston_lfo3p31wlx_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'vestel_dwa4510b3x_price', availName: 'vestel_dwa4510b3x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'vestel_dwfa4310b1x_price', availName: 'vestel_dwfa4310b1x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'vestel_dwfa4310b1dx_price', availName: 'vestel_dwfa4310b1dx_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'samsung_dw60dg790fslfh_price', availName: 'samsung_dw60dg790fslfh_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'whirlpool_wfo3t133pfx_price', availName: 'whirlpool_wfo3t133pfx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'whirlpool_wfo3o41plxuk_price', availName: 'whirlpool_wfo3o41plxuk_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'lg_dfb512fp_price', availName: 'lg_dfb512fp_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'lg_dfb425fp_price', availName: 'lg_dfb425fp_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lfp5p31wltx',
        brand: 'Ariston',
        model: 'LFP 5P31 WLT X',
        existsName: 'ariston_lfp5p31wltx_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'vestel_dwa4510b3x_price', availName: 'vestel_dwa4510b3x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'vestel_dwfa4310b1x_price', availName: 'vestel_dwfa4310b1x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'vestel_dwfa4310b1dx_price', availName: 'vestel_dwfa4310b1dx_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'samsung_dw60dg790fslfh_price', availName: 'samsung_dw60dg790fslfh_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'whirlpool_wfo3t133pfx_price', availName: 'whirlpool_wfo3t133pfx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'whirlpool_wfo3o41plxuk_price', availName: 'whirlpool_wfo3o41plxuk_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'lg_dfb512fp_price', availName: 'lg_dfb512fp_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'lg_dfb425fp_price', availName: 'lg_dfb425fp_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bdfn36651xc',
        brand: 'beko',
        model: 'BDFN36651XC',
        existsName: 'beko_bdfn36651xc_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'vestel_dwa4510b3x_price', availName: 'vestel_dwa4510b3x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'vestel_dwfa4310b1x_price', availName: 'vestel_dwfa4310b1x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'vestel_dwfa4310b1dx_price', availName: 'vestel_dwfa4310b1dx_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'samsung_dw60dg790fslfh_price', availName: 'samsung_dw60dg790fslfh_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'whirlpool_wfo3t133pfx_price', availName: 'whirlpool_wfo3t133pfx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'whirlpool_wfo3o41plxuk_price', availName: 'whirlpool_wfo3o41plxuk_avail' },
          { brand: 'LG', model: 'DFB512FP.APZPELF Direct Drive', ref: '370 JD', priceName: 'lg_dfb512fp_price', availName: 'lg_dfb512fp_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'lg_dfb425fp_price', availName: 'lg_dfb425fp_avail' },
        ],
      },
      {
        id: 'card_dishwashers_beko_bdfn39410xc',
        brand: 'beko',
        model: 'BDFN39410XC',
        existsName: 'beko_bdfn39410xc_exists',
        competitors: [
          { brand: 'Vestel', model: 'DWA4510B3X', ref: '—', priceName: 'vestel_dwa4510b3x_price', availName: 'vestel_dwa4510b3x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1X', ref: '298 JD', priceName: 'vestel_dwfa4310b1x_price', availName: 'vestel_dwfa4310b1x_avail' },
          { brand: 'Vestel', model: 'DWFA4310B1DX', ref: '330 JD', priceName: 'vestel_dwfa4310b1dx_price', availName: 'vestel_dwfa4310b1dx_avail' },
          { brand: 'Samsung', model: 'DW60DG790FSLFH', ref: '—', priceName: 'samsung_dw60dg790fslfh_price', availName: 'samsung_dw60dg790fslfh_avail' },
          { brand: 'Whirlpool', model: 'WFO 3T133 PF X', ref: '—', priceName: 'whirlpool_wfo3t133pfx_price', availName: 'whirlpool_wfo3t133pfx_avail' },
          { brand: 'Whirlpool', model: 'WFO 3O41 PL X UK', ref: '—', priceName: 'whirlpool_wfo3o41plxuk_price', availName: 'whirlpool_wfo3o41plxuk_avail' },
          { brand: 'LG', model: 'DFB425FP.APZPELF Direct Drive', ref: '485 JD', priceName: 'lg_dfb425fp_price', availName: 'lg_dfb425fp_avail' },
        ],
      },
      {
        id: 'card_dishwashers_ariston_lic3b26',
        brand: 'Ariston',
        model: 'LIC 3B+26',
        existsName: 'ariston_lic3b26_exists',
        competitors: [
          { brand: 'Whirlpool', model: 'WIE 2B19 N UK', ref: '—', priceName: 'whirlpool_wie2b19nuk_price', availName: 'whirlpool_wie2b19nuk_avail' },
          { brand: 'Whirlpool', model: 'WBC 3C34 PF X', ref: '—', priceName: 'whirlpool_wbc3c34pfx_price', availName: 'whirlpool_wbc3c34pfx_avail' },
        ],
      },
    ],
  },
  {
    icon: '❄️',
    title: 'الفريزر القائم',
    sub: 'Upright Freezers',
    products: [
      {
        id: 'card_freezers_beko_rfsa240m23x',
        brand: 'beko',
        model: 'RFSA240M23X',
        existsName: 'beko_rfsa240m23x_exists',
        competitors: [
          { brand: 'Midea', model: 'MDRU229FZF01', ref: '—', priceName: 'midea_mdru229fzf01_price', availName: 'midea_mdru229fzf01_avail' },
          { brand: 'Midea', model: 'MDRU229FZF02', ref: '180 JD', priceName: 'midea_mdru229fzf02_price', availName: 'midea_mdru229fzf02_avail' },
          { brand: 'Vestel', model: 'RN270FR3EI-BG', ref: '266 JD', priceName: 'vestel_rn270fr3eibg_price', availName: 'vestel_rn270fr3eibg_avail' },
          { brand: 'Vestel', model: 'RN360FR3EI-X', ref: '275 JD', priceName: 'vestel_rn360fr3eix_price', availName: 'vestel_rn360fr3eix_avail' },
        ],
      },
      {
        id: 'card_freezers_beko_rfnm200e20w',
        brand: 'beko',
        model: 'RFNM200E20W',
        existsName: 'beko_rfnm200e20w_exists',
        competitors: [
          { brand: 'Ignis', model: 'CSTNF231 (Three Years Warranty)', ref: '—', priceName: 'ignis_cstnf231_price', availName: 'ignis_cstnf231_avail' },
          { brand: 'Vestel', model: 'RN270FR3EI-BG', ref: '266 JD', priceName: 'vestel_rn270fr3eibg_price', availName: 'vestel_rn270fr3eibg_avail' },
          { brand: 'Tekmaz', model: 'NAS-6DS', ref: '315 JD', priceName: 'tekmaz_nas6ds_price', availName: 'tekmaz_nas6ds_avail' },
        ],
      },
      {
        id: 'card_freezers_beko_rfne340l31xb',
        brand: 'beko',
        model: 'RFNE340L31XB',
        existsName: 'beko_rfne340l31xb_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN360FR3EI-X', ref: '275 JD', priceName: 'vestel_rn360fr3eix_price', availName: 'vestel_rn360fr3eix_avail' },
          { brand: 'Newton', model: '355Usm  (With Screen)', ref: '—', priceName: 'newton_355usm_price', availName: 'newton_355usm_avail' },
          { brand: 'Newton', model: '466Usm  (With Screen)', ref: '—', priceName: 'newton_466usm_price', availName: 'newton_466usm_avail' },
          { brand: 'Ignis', model: 'CST381S (Two Years Warranty)', ref: '—', priceName: 'ignis_cst381s_price', availName: 'ignis_cst381s_avail' },
          { brand: 'Hisense', model: 'FV356N4ASU With 10 Years Compressor Warranty (With Screen)', ref: '365 JD', priceName: 'hisense_fv356n4asu_price', availName: 'hisense_fv356n4asu_avail' },
          { brand: 'Indesit', model: 'UI6 F1T S', ref: '—', priceName: 'indesit_ui6f1ts_price', availName: 'indesit_ui6f1ts_avail' },
          { brand: 'Indesit', model: 'UI8 F1D X (With Screen)', ref: '—', priceName: 'indesit_ui8f1dx_price', availName: 'indesit_ui8f1dx_avail' },
          { brand: 'Samsung', model: 'RZ32M71207F/SG With 20 Years Compressor Warranty (With Screen)', ref: '—', priceName: 'samsung_rz32m71207fsg_price', availName: 'samsung_rz32m71207fsg_avail' },
        ],
      },
      {
        id: 'card_freezers_beko_rfne451xb',
        brand: 'beko',
        model: 'RFNE451XB Inverter Compressor with 10 Years Warranty (With Screen)',
        existsName: 'beko_rfne451xb_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN440FR3F-DX  (With Screen)', ref: '380 JD', priceName: 'vestel_rn440fr3fdx_price', availName: 'vestel_rn440fr3fdx_avail' },
          { brand: 'Vestel', model: 'RN440FR3F-X  (With Screen)', ref: '380 JD', priceName: 'vestel_rn440fr3fx_price', availName: 'vestel_rn440fr3fx_avail' },
          { brand: 'Benkon', model: 'FR-BN371S  (With Screen)', ref: '—', priceName: 'benkon_frbn371s_price', availName: 'benkon_frbn371s_avail' },
          { brand: 'Blumatic', model: 'BUF300X', ref: '—', priceName: 'blumatic_buf300x_price', availName: 'blumatic_buf300x_avail' },
          { brand: 'Sharp', model: 'SJ-SFR415-HS2/3', ref: '—', priceName: 'sharp_sjsfr415hs23_price', availName: 'sharp_sjsfr415hs23_avail' },
          { brand: 'Samsung', model: 'RZ32M71207F/SG With 20 Years Compressor Warranty (With Screen)', ref: '—', priceName: 'samsung_rz32m71207fsg_price', availName: 'samsung_rz32m71207fsg_avail' },
        ],
      },
      {
        id: 'card_freezers_beko_rfne448e35xp',
        brand: 'beko',
        model: 'RFNE448E35XP Inverter Compressor with 10 Years Warranty (With Screen)',
        existsName: 'beko_rfne448e35xp_exists',
        competitors: [
          { brand: 'Vestel', model: 'RN600FR4F-X  (With Screen)', ref: '506 JD', priceName: 'vestel_rn600fr4fx_price', availName: 'vestel_rn600fr4fx_avail' },
        ],
      },
    ],
  },
];